### ISSUE TITLE
The result is a ? in the sgf file

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#105]
Hi,

I let 2 models to play against each other in gogui, the sgf file is as follows:

(;FF[4]CA[UTF-8]AP[gogui-twogtp:1.4.9]SZ[9]
KM[6.5]PB[Somebot-000011-model]PW[Somebot-000012-model]DT[2018-02-20]
C[Black command: python3 main.py gtp --readouts=100 -l models/000011-model
White command: python3 main.py gtp --readouts=100 -l models/000012-model
Black version: 0.1
White version: 0.1
Result[Black\]: ?
Result[White\]: ?

Why is the result a ? for this game?

Thank you very much

**Comment by amj** [comment]
Minigo doesn't support the 'final_score' GTP command, and gogui-twogtp won't adjudicate the result.  Supporting additional GTP commands is tracked in #46 

If you run via `python main.py selfplay ...` the result will be correctly set in the SGF.

**Comment by weedwind** [comment]
I simply changed the instruction which let a model play against gnugo to let 2 models play instead. My script is:

#!/bin/bash
#BLACK="gnugo --mode gtp"    This is the original code
BLACK="python3 main.py gtp --readouts=100 -l models/000011-model"
WHITE="python3 main.py gtp --readouts=100 -l models/000012-model"
TWOGTP="gogui-twogtp -black \"$BLACK\" -white \"$WHITE\" -games 10\
  -size 9 -alternate -sgffile gnugo"
gogui -size 9 -program "$TWOGTP" -computer-both -auto

In the game record whose result is a ?, I saw that the game was very short, like this:
;B[ed];W[];B[]

whereas in another game which has a normal result (such as W+R), the game record seems good, like this:

;B[ed];W[gd];B[dc];W[];B[fa];W[];B[fc];W[];B[db];W[]
;B[de];W[];B[ce];W[if];B[hc];W[];B[ef];W[fg];B[dg];W[dh]
;B[hd];W[ci];B[af];W[id];B[ga];W[gf];B[eg];W[bd];B[fe];W[he]
;B[bg];W[fh];B[ch];W[da];B[ca];W[gb];B[eh];W[be];B[cb];W[ah]
;B[fb];W[ib];B[ac];W[bi];B[ei];W[bc];B[gh];W[bf];B[ae];W[]
;B[ih];W[ad];B[ag];W[ge];B[hi];W[ab];B[ha];W[hb];B[gc];W[]
;B[ba];W[fi];B[gi];W[gg];B[cg];W[hf];B[cd])

So it seems that some games were not properly played to get a result?

**Comment by amj** [comment]
When running with gogui-twogtp, twogtp is acting as the intermediary between the two programs running in GTP mode, letting them 'talk' to each other.  Twogtp doesn't know how to score the board.  So when the game ends by counting, twogtp doesn't know the result.  But when one player resigns, twogtp is able to see that as a GTP response and put it in the sgf.

Incidentally, for young, noisy networks, they will sometimes pass very early in the game.  This is normal, and eventually they learn better :)
