### ISSUE TITLE
Why do we only generate 1 model using 500K games?

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#106]
If my understanding is right, we use the latest 500K games to train a new model (trained for 1000 batches with 2048 moves/batch), and then use the new model to generate new games. I am not sure why don't we go through all the 500K games to generate a new model?

**Comment by amj** [comment]
I don't understand the question.

**Comment by weedwind** [comment]
@amj I mean why do we only use 1000 batches of moves from the latest 500K games to generate a model, rather than training the model for much more batches until we use all the moves in 500K games to generate a model?

**Comment by amj** [comment]
the short answer is because that's what they say to do in the paper :)

The longer answer is a guess:  I assume that if we train on all 500k*250 = 125M positions that the value network will overfit, as many of the positions correlate with each other.  It would also take > 50 times as long to train!
