### ISSUE TITLE
Feature: nice gogui/GTP extensions

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#11]
Our GTP code has a nice place to put in some GTP extensions in gtp_extensions.py
It should be pretty easy to hook up some code to dump things in the format gogui/sabaki like to see for variations or heatmaps or whatever.

it'd be a good starter project for someone interested in getting acquainted with the codebase.

**Comment by axao** [comment]
Hi, is it possible to test minigo with sabaki or softwares like this ?

**Comment by amj** [comment]
I know we wrote some extensions to use GoGui, no idea if the visualizations work with Sabaki.  The difficult bit is making sure Sabaki runs the engine within the correct python virtualenv, with the correct env vars, etc.

**Comment by amj** [comment]
yes, minigo runs with sabaki/gogui.  It also runs with our own minigui.
