### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by greatken999** [tensorflow/minigo#114]
I run :python3 local_rl_loop.py   to test minigo at local ,get error info:
Traceback (most recent call last):
  File "local_rl_loop.py", line 97, in <module>
    rl_loop()
  File "local_rl_loop.py", line 87, in rl_loop
    main.gather(input_directory=selfplay_dir, output_directory=gather_dir)
  File "/xxx/minigo/main.py", line 282, in gather
    with open(meta_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw8wakbq7/data/training_chunks/meta.txt'

**Comment by brilee** [comment]
Those lines in the stack trace don't match my current version of the code. Can you reproduce the error after git pull'ing the latest code?

**Comment by greatken999** [comment]
yes ,it's last code

**Comment by brilee** [comment]
Can you repost the stack trace you get with the latest code?

**Comment by greatken999** [comment]
fixed
