### ISSUE TITLE
Can minigo train a network that goes for max points? 

### ISSUE THREAD

**Issue by hydrogenpi** [tensorflow/minigo#120]
Essentially we already know Google can do AlphaGo almost god-like at 5000+ ELO with AlphaGoZero. 

What is more interesting would be if each iteration of the network can be released to the public as it gets stronger almost like how with leelazero anyone can download any version/strength of the network at any arbitrary points. 

But perhaps even more intriguing is training a "human like" bot at all different levels of strengths, from say 35 kyu all the way to upper pro levels. This would help in that new comers to the game won't have to play online anymore and can just train/use offline bots to help them with their progression.

But another interesting thing to try is to train a network that is very strong but always goes for MAX points, and that in the game itself it dynamically gauges and adjusts to the strength of the opponent (be it a bot or a real human) and the objective is not only to win, but to do so with the MAX points possible. 

For example. lets say this trained network is high pro level, and it figures out within the first 50 moves that it is playing against a double digit kyu, then it would proceed to play "troll" moves that takes the offensive and ends up with the most amounts of points as possible instead of playing conservative 

Is it possible to train a network like this? To go for MAX POINTS but also to be able to somehow gauge the relative strength of the opponent in real-time in the live game itself and then each time dynamically adjust its "offensive" level in order to end up with max points while still winning? (and not overdoing it that it actually loses the game etc)

**Comment by brilee** [comment]
It's a good question, and I have some thoughts on this matter. I'd also like to reserve the minigo issue tracker for actionable issues like bug reports / near-term feature planning. If you repost this on reddit.com/r/cbaduk, I'll answer there.
