### ISSUE TITLE
DataLossError (see above for traceback): Invalid size in bundle entry: key global_step; stored size 4; expected size 8

### ISSUE THREAD

**Issue by brilee** [tensorflow/minigo#121]
With the estimator rewrite, the type signature of the dual_net remained exactly the same, with one change: global_step is now an int64 instead of an int32. This is causing our existing savedmodels to fail to load with DataLossError. We should attempt to recover gracefully in such situations.

**Comment by brilee** [comment]
(Also, our published 9x9 models no longer work with latest code for the same reason.

**Comment by amj** [comment]
oh noooooooo :sob:  What does 'graceful recovery' look like?  Do we hardcode testing for the global_step conversion?   Backfill all the models?

**Comment by brilee** [comment]
Hm. Probably a backfill would be the easiest thing to do, although we'll continue to have a long tail of people saying that their code now doesn't work any more. You'd have to backfill the models that people have downloaded to their hard drives, which is a harder problem.

Not sure that we get much control over the model loading process with Estimator, though, so backfilling is probably the only option we have.

**Comment by amj** [comment]
if all our docs point to model paths like `gs://minigo-pub/v3-9x9/models/...` then it's not too bad?  
Assuming we backfill, anyone hitting the bug can re-download the model, so maybe we could leave a `except tf.DataLossError: print("Go look at this issue on GH and/or redownload this model")` around the loading code.

**Comment by brilee** [comment]
Here is a snippet that fixes the savedmodel. It should be easy enough to script this to update all of our published models. Anybody running into this problem can also run this snippet locally.

```python
import tensorflow as tf
import dual_net

save_file = 'lightning/000199-lightning'
dest_file = 'lightning/000199-lightning-upgrade'
features, labels = dual_net.get_inference_input()
dual_net.model_fn(features, labels, tf.estimator.ModeKeys.PREDICT, dual_net.get_default_hyperparams())
sess = tf.Session()

# retrieve the global step as a python value
ckpt = tf.train.load_checkpoint(save_file)
global_step_value = ckpt.get_tensor('global_step')


# restore all saved weights, except global_step
from tensorflow.python.framework import meta_graph
meta_graph_def = meta_graph.read_meta_graph_file(save_file + '.meta')
stored_var_names = set([n.name
    for n in meta_graph_def.graph_def.node
    if n.op == 'VariableV2'])
print(stored_var_names)
stored_var_names.remove('global_step')
var_list = [v for v in tf.global_variables()
    if v.op.name in stored_var_names]
tf.train.Saver(var_list=var_list).restore(sess, save_file)

# manually set the global step
global_step_tensor = tf.train.get_or_create_global_step()
assign_op = tf.assign(global_step_tensor, global_step_value)
sess.run(assign_op)

# export a new savedmodel that has the right global step type
tf.train.Saver().save(sess, dest_file)
```

**Comment by amj** [comment]
Ok i'll work on fixing all the 9x9 models.

**Comment by amj** [comment]
I've validated the snippet works.  I'm going to do an in-place upgrade (i.e., not tacking '-upgraded' on the end) and update all the 9x9 models.  

I also verified that the selfplay & evaluate code works with the estimator rewrite (not that i doubted it, but it was a good sanity check on my backfill op :)

**Comment by amj** [comment]
This op is running on all the models in gs://minigo-pub/v3-9x9/models

**Comment by amj** [comment]
Re-opening -- i haven't fixed the 19 models.
