### ISSUE TITLE
Not very clear how the data pipeline works

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#124]
Hi, I am reading read_tf_records function in preprocessing.py. I am not sure if I understand the data pipeline correctly.  To generate a model, we use the latest 500K games with a total of 125M positions (suppose there are 250 positions in each game), and by the function gather(), these positions are saved in a bunch of *.tfrecord.zz training chunks, with 10000 positions in each tf record (EXAMPLES_PER_RECORD = 10000). Then, the function read_tf_records first shuffle these tfrecord filenames, then it reads 16 tf.examples (positions) by the function record_list.interleave from each tf record. Then it loads SHUFFLE_BUFFER_SIZE this many positions into memory at one time, and forms random batches from this buffer. Is my understanding correct? I am not sure does record_list.interleave() just read 16 positions from each tf record and ignore the rest? Also, how does dataset.shuffle() function form a buffer of 4M positions?

**Comment by amj** [comment]
you seem to be reading it mostly correct - the clarifications are that record_list.interleave() interleaves reading positions 16 at a time until the whole file is complete; those are also filtered, so only ~5% of the positions of a game will be used.  Dataset.shuffle then shuffles this whole collection of positions.

**Comment by amj** [comment]
Feel free to reopen if there are more questions :)
