### ISSUE TITLE
Leela-zero weights

### ISSUE THREAD

**Issue by bellau** [tensorflow/minigo#126]
Is it possible to re-use leela-zero weights with minigo ?

**Comment by amj** [comment]
Possibly, but it might be tough.  See the [conversation here](https://github.com/gcp/leela-zero/issues/785#issuecomment-361711962)

**Comment by bellau** [comment]
I was hoping to do some experiments with leelaz model using python/TF (far easier than c++). For now, i use modified leelaz training code to run the model ( https://github.com/bellau/leelaz-toys ).
Thank you @amj !
