### ISSUE TITLE
AccessDeniedException: 403 

### ISSUE THREAD

**Issue by gino2013** [tensorflow/minigo#136]
When I run "gsutil ls gs://minigo/models | tail -3", I get message:"AccessDeniedException: 403 xxxxx@gmail.com does not have storage.objects.list access to bucket." 
How can I fix the access denied exception problem?

**Comment by amj** [comment]
try `gsutil ls gs://minigo-pub/v3-9x9/models`

**Comment by gino2013** [comment]
@amj thanks a lot! this works fine.
