### ISSUE TITLE
Rewrite self-play in more performant language

### ISSUE THREAD

**Issue by Kashomon** [tensorflow/minigo#14]
I've chatted in passing with @amj about this and I wanted to discuss it more formally. Self-play is, as I understand it, the most important part to speed up since more-games-faster means you can train the go-bot faster.

Here are a couple of options that I would consider:

* C++
* Go
* Rust

Some factors:

Currently, we're leaning towards a rewrite in Go (maybe), since we believe that would be simple / easy to follow. Also, I've at least used Go quite a bit on Kubernetes, so there's an experience factor too.

**Comment by marcocalignano** [comment]
Hi, there is PyQt, that is a module for integrating python into Qt code. So using C++ you could start small and use all the python code and then slowly replacing the python with other C++ code.

**Comment by ViktorM** [comment]
C++ is the best choice I think.

**Comment by tommadams** [comment]
I've made a very early start on a C++ rewrite.

**Comment by marcocalignano** [comment]
@tommadams can we see the code?

**Comment by tommadams** [comment]
As soon as I have something interesting to show, then yes. I've literally only just started working on it :)

**Comment by tommadams** [comment]
I've just merged in the first stage in the C++ rewrite, under the cc/ subdirectory. It's currently just contains Position logic and some basic testing of the Tensorflow API. I'm in the process of porting the MCTS code now.

**Comment by tommadams** [comment]
C++ implementation is pretty much done!
