### ISSUE TITLE
How to coordinate selfplay and train

### ISSUE THREAD

**Issue by zchen0211** [tensorflow/minigo#142]
Hi, 

Excuse me. The code looks great and is very helpful! :) I have a question about machine setup:

I think there is two main loops running simultaneously. One is selfplay run by a lot of GPU machines; another is CNN training on the data generated by selfplay.

Which is faster? Which is waiting for the other? I mean if the selfplay is faster, it will generate 10k games first and then stop for the CNN trainer to converge; if the CNN training is faster, it will wait for the data to be enough before training to avoid overfitting?

**Comment by amj** [comment]
The training is almost always 'waiting' for games from selfplay.  In an ideal situation, they are perfectly balanced; there are enough selfplay workers to make new data fast enough for the training job.

In practice, '10k' is a number arrived at by guessing from the numbers in the AGZ & AZ papers.  It could be it would work just fine with more or less games.  Also, in practice, there are other steps like performing validation, or gathering the new data and preprocessing it, or selecting the positions uniformly, that could become a non-negligible part of the pipeline.

Overall, it seems like the entire pipeline needs to be looked at holistically, and tracking the actual objective performance is more relevant; once that is accomplished then optimizing or making the pipeline more efficient becomes useful.

Hope this helps :)

**Comment by zchen0211** [comment]
Oh. Got it. Thank you! :)
