### ISSUE TITLE
Ladder capture & escape feature

### ISSUE THREAD

**Issue by zhichaoshu** [tensorflow/minigo#143]
Have anyone implemented the ladder capture and escape features mentioned in the first Alpha Go paper? I didn't find that in minigo or MUGO code. Any suggestions would be appreciated.

**Comment by amj** [comment]
Nope, these weren't in the initial MuGo.  The hard part is computing the feature efficiently, as it will need to be done at each leaf during search.

It might be easier to use a liberty feature instead, which will need to be computed anyway for establishing the state transitions in the MCTS.

**Comment by zchen0211** [comment]
Hi, I think this is a very interesting point. Is the ladder understood by the CNN or the MCTS? According to @amj, it is understood immediately during CNN training with seen selfplay examples?

**Comment by brilee** [comment]
I don't think the CNN can compute ladders, from my experience. It can get there with a deep enough MCTS search, but even then it struggles due to liberty propagation issues.

**Comment by amj** [comment]
closing as obsolete.
