### ISSUE TITLE
Choose a python code formatter and format the code

### ISSUE THREAD

**Issue by Kashomon** [tensorflow/minigo#15]
We should choose a code-formatter and use it! It helps a lot to ease the burden of day-to-day style considerations. Preferably something that implements the Pep8 guide.

https://pypi.python.org/pypi/autopep8 is a good candidate since that's hosted on pypi. And, selfishly, we have builtin support as part of our Vim CodeFmt plugin.

**Comment by brilee** [comment]
Is this issue different from https://github.com/tensorflow/minigo/issues/35 ? @Kashomon

**Comment by amj** [comment]
closing this, reopen as needed
