### ISSUE TITLE
question about graph

### ISSUE THREAD

**Issue by herazul** [tensorflow/minigo#156]
It may be better than reddit to ask, so here you go, i ask it here :D

Did you change something ? This morning the graph looks different, like there is less net taken in account.

Otherwise i had an idea that may be simple to test but i don't know if it's doable : train your net with leela code on your last windows and match it versus yours, to see if it give similar strength result or not.

**Comment by amj** [comment]
Yep, there's a checkbox labeled 'filter bad models'; it takes the best of each set of 4 models only, similar to what it would look like if we'd used gating.

**Comment by amj** [comment]
Training our net on leela code is plausible but would require converting it all to our format; it's definitely a possibility.
