### ISSUE TITLE
refactor minigui extensions

### ISSUE THREAD

**Issue by brilee** [tensorflow/minigo#171]
I stumbled on some of the copy-pasted code in gtp_extensions and it's a bit tricky to work around with the new hyperparam work.

Can you at some point refactor this so that the search logic code isn't copy-pasted?

One suggestion for how this might work is for strategies.MCTSPlayerMixin.suggest_move can have callbacks registered, and by default those callbacks do nothing, but gtp_extensions can hook into those callbacks to retrieve debug stats.

**Comment by tommadams** [comment]
Yeah, sorry about that :/
I was rushing to get the demo ready in time for the conference.

I'll clean it up this week.

**Comment by tommadams** [comment]
I am halfway through, but I got sidetracked by other things. It's at the top of my list, so I'll likely get to it this afternoon or tomorrow.
