### ISSUE TITLE
presubmit tests should check the cc/ code compiles

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#179]
at some point we should figure out how to have presubmit tests for the code under cc/

we've got a dockerfile that should Just Work assuming no one's broken the build.  Maybe there's an easy way to use that?

**Comment by amj** [comment]
@Kashomon could you chime in on what would be needed here?

**Comment by Kashomon** [comment]
The prow tests are just running: https://github.com/tensorflow/minigo/blob/master/test.sh

via this wrapper: https://github.com/tensorflow/minigo/blob/master/testing/bootstrap_v2.sh

and which gets configured in prow here: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L5584

and put into the UI here: https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L2035 (several places in this file)

The final piece of the puzzle is this jobs JSON file, which links the job (the prow config) with the actually command it's running:
https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L13170

**Comment by Kashomon** [comment]
I already had some docs in minigo/testing. But I'll add some more

**Comment by amj** [comment]
we have a new base image that has the tensorflow headers & .so's ready to rock, the problem is the new code is layered in as a mount volume, so some sort of magic needs to either get the code from the new volume into /app/cc, or the headers/so's from /app/cc to wherever the code-to-test gets mounted.

**Comment by amj** [comment]
this happens now.
