### ISSUE TITLE
Facebook open sources AlphaGo clone with weights and code, claims much stronger than LZ0

### ISSUE THREAD

**Issue by hydrogenpi** [tensorflow/minigo#200]
https://github.com/pytorch/ELF/issues/1

**Comment by hydrogenpi** [comment]
How much stronger is it than leela zero on only one playout?


https://github.com/gcp/leela-zero/issues/1311

https://github.com/pytorch/ELF/issues/1

**Comment by amj** [comment]
Can you explain what action you'd like to see here?  How is this an issue for minigo?

**Comment by amj** [comment]
Ok, it's been a week -- closed pending clarification.
