### ISSUE TITLE
"play white d4" results in black stone at d4

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#203]
gtp doesn't seem to allow white / black to play out of turn. not sure if this is expected behavior.

**Comment by tommadams** [comment]
That's working as implemented, see https://github.com/tensorflow/minigo/blob/master/gtp_wrapper.py#L71

I'm not sure why the `accomodate_out_of_turn` call is commented out though. Andrew?

**Comment by amj** [comment]
it was probably broken during my early rewrite of the mcts in dec 2017
where i was shooting for a minimum working example;

That said, i think our position objects should be tolerant to strange
orderings.  the `recent` objects have the color in the tuple, IIRC... so i
think it'll work?  `accomodate_out_of_turn` used to have a bunch of logic
in go.py that would flip the board color by multiplying it all by -1... so
that logic might be suspicious

**Comment by amj** [comment]
Our engine isn't really set to deal with out of order play commands, as the input features to the NN include the move history planes.  In theory, the network should be robust to the move-history planes having out-of-sequence moves but in practice who knows what sort of weird behavior it might cause.  i think the right thing to do is to return a gtp error somehow.
