### ISSUE TITLE
black passes for loss without thinking

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#205]
[https://imgur.com/a/jhOhvKs](https://imgur.com/a/jhOhvKs)

final score requires [my/brian's patch of gtp](https://github.com/jtauber/gtp/pull/9/files)

**Comment by amj** [comment]
this is probably related to merging in https://github.com/tensorflow/minigo/blob/master/gtp_wrapper.py#L121 and screwing up the default parameters for creating our Player obj.

**Comment by sethtroisi** [comment]
I think the root issue here is that you can't run from master (see backfill).
