### ISSUE TITLE
cronus is open source, game over every go home

### ISSUE THREAD

**Issue by hydrogenpi** [tensorflow/minigo#225]
One benefit of pushing forward open bots that are superhuman is it may force the hand of others as well, now that Fb and Tencent have open sourced their bots that are both much stronger than LZ, maybe Deepmind will come back for thirds and get a fourth place prize in openness to cheapshot score one last PR hooray for Google by open sourcing their AGZ weights to spit in fb's face and to show whos the alpha by mastering the Chinese competition once again.. open competition is good for go. This is truly the end of a human era.

**Comment by john45678** [comment]
Minigo is a exciting project in its own right, and may equal or exceed Cronus . So why stop, theres room for every new computer go program.
