### ISSUE TITLE
Should do cycle detection/superko

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#235]
i.e. triple kos.

**Comment by sethtroisi** [comment]
if you have local sgfs...

find sgf/ -wholename '*/clean/*sgf' | tqdm > clean_sgfs
< clean_sgfs parallel -m -l100 sgfcheck |& tee results
grep -v 'cycle' results

I think it's 48,000 out of 2666000 games or 1.8% of games

**Comment by sethtroisi** [comment]
Most of there are not triple kos and instead are https://senseis.xmp.net/?SendingTwoReturningOne

**Comment by brilee** [comment]
dupe of #8
