### ISSUE TITLE
Multithreading CC Selfplay

### ISSUE THREAD

**Issue by marcocalignano** [tensorflow/minigo#250]
I was looking at the C++ code for the self play and I was wondering if it could be enhance to be multithreading to generate more output. I guess a solution for multiple OS has to be found or is it to be assumed that it runs only on Linux (unix) clients?

**Comment by tommadams** [comment]
Yes, we plan on adding multithreading support soon.

**Comment by tommadams** [comment]
Although I should clarify that we're planning on adding multithreading specifically for Cloud TPUs.

We generally see >95% GPU utilization during single threaded selfplay, so it's not clear that adding more threads will improve GPU selfplay performance significantly.

**Comment by marcocalignano** [comment]
Unfortunately I cannot compile tensor flow on my machine otherwise I would implement that.

**Comment by amj** [comment]
@marcocalignano Tom's got a PR in progress for the multithreading; what problems are you having compiling tensorflow on your machine?

**Comment by marcocalignano** [comment]
Basically I have Kubuntu 18.04 and the default compiler is gcc-7 which apparently is not really liked by the `configure_tensorflow.sh` script. 
I tried to change the default gcc links to point to gcc-6 but I still have some problem with c++ code, I guess I didn't change enough. I will have to try a bit more!

**Comment by tommadams** [comment]
Can you try compiling with Bazel 0.11.1 (and gcc-6)? We have experienced some issues with later versions: https://docs.bazel.build/versions/master/install.html
