### ISSUE TITLE
main.py train-dir parameter

### ISSUE THREAD

**Issue by gino2013** [tensorflow/minigo#252]
When I run the training job in README.md as following:

BOARD_SIZE=19 python3 main.py train-dir \
  estimator_working_dir \
  gs://$BUCKET_NAME/data/training_chunks \
  gs://$BUCKET_NAME/models/000001-somename \
  **--generation-num=1** 

the error happens, the option  **"--generation-num=1"** seems not to be supported anymore? 
I check "main.py train-dir -h" as below, there are only three parameters with train-dir: 

usage: main.py train-dir [-h] working-dir chunk-dir model-save-path
positional arguments:
  working-dir      tf.estimator working directory.
  chunk-dir        Directory where training chunks are.
  model-save-path  Where to export the completed generation.

**Comment by amj** [comment]
Yep, the generation argument is no longer needed -- sorry for the trouble!
