### ISSUE TITLE
HEAD has bad dependency on import tpu.bfloat16 

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#259]
README says: pip3 install "tensorflow-gpu>=1.7,<1.8"

bfloat16 seems to have been added in 1.8
https://github.com/tensorflow/tensorflow/tree/r1.8/tensorflow/contrib/tpu/python/tpu

**Comment by tommadams** [comment]
#256 will update the docs just as soon as I fix my borked local repo and push it :)
