### ISSUE TITLE
Improve worker/training balance.

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#26]
How should we handle self-play balance with training?

AGZ 20 block
5M games, 700 checkpoints = ~7k games/checkpoint

AGZ 40 block
29M games, 3.1M batch = 3100 checkpoints. = ~10k games/batch???

but also:
"In each iteration, αθ∗ plays 25,000 games of self-play" (AGZ)
So perhaps: the evaluator passes approximately 1/3-1/4 of all checkpoints.

AZ: 700k steps of double size (4098)
21M games.  no 'checkpoints'.  Would be equivalent to 15k games/checkpoint in AGZ reckoning

These seem to suggest that having *more* games per generation is preferable, and suggests there's not as much concern about the number of generations represented in the training window.

So, i'd like this issue to resolve:
 - how we should target our worker/playout balance
 - what changes we'll need to make to achieve it.  In particular, if our training/worker jobs are subject to pre-emption or are otherwise, uh, *not robust*, i'd like to brainstorm what we can do to keep the two jobs in balance.

**Comment by amj** [comment]
At a minimum, i'd like a way for workers to backoff/go to sleep if there's enough games for the given model, and a way for the trainer to wait for there to be enough new games before training.  Literally anything would be an improvement on the current method.

**Comment by brilee** [comment]
two problems:
- trainer dies; workers generate obscene number of games for just one generation
- workers get pre-empted; trainer continues training on the same data repeatedly, potentially overfitting.

solutions
- (for trainer dying): cap number of games per generation. (Q: you would want to know the sum of #games played and #games currently being played for a given generation; this is not easy to do. how can we prevent overshooting # of games? does this even matter? If number of workers << number of games desired, then there's only so much we can overshoot by.)
- (for workers dying): only initiate training if there are sufficiently many new games.

**Comment by brilee** [comment]
Another thought: if we have 1000 workers, each completing a game every 5 +/- 3 minutes, then why not just output checkpoints every 5 minutes. After all, if a worker is gonna start a new game, why not just grab the latest weights? So having 10,000 games in a generation seems unnecessarily stale. In a regime where each worker only plays 1 game per generation on average, the above solutions may work less well.

**Comment by amj** [comment]
Partially addressed by #75 .

**Comment by amj** [comment]
I'm ok targeting 10k games/generation for this one, not worrying about getting fewer, and putting a hard cap of 15k per.  @brilee, any further thoughts?

**Comment by brilee** [comment]
we have some crude backoff mechanisms now.
