### ISSUE TITLE
num_readouts=1 seems broken

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#260]
genmove b
A19
genmove w
Illegal move (tries to play on A19 again?)

**Comment by amj** [comment]
which engine?

**Comment by sethtroisi** [comment]
I thought it was python.
Offline Andrew thought it's  might be a bad "<" vs "<=" from this [code](https://github.com/tensorflow/minigo/blob/master/cc/mcts_player.cc#L129)

**Comment by sethtroisi** [comment]
BOARD_SIZE=19 python3 main.py gtp -l models/000303-olympus -v 3 --resign_threshold=-0.98 --num_readouts 1 --parallel_readouts=1

**Comment by tommadams** [comment]
Reopening this issue:

- C++ exhibits the same illegal move behaviour with `--num_readouts=1`.
- As Seth mentioned, Python behaviour with `--num_readouts=1` seems weird.

**Comment by tommadams** [comment]
*sigh* C++ soft pick also has problems when num_readouts=1.

**Comment by amj** [comment]
@tommadams i'm assuming this is fixed
