### ISSUE TITLE
Need to do rotations in TPU training

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#265]
see the discusson on #163 .  We can't re-open that, so let's track the work here.

**Comment by sethtroisi** [comment]
@brilee, andrew suggested doing rotation when we create the golden chunks which I think is a workable solution for the rl_loop setup

**Comment by brilee** [comment]
Oh - that's a great point, since we expect each golden chunk to be single-use anyway. I like this idea.

**Comment by amj** [comment]
@sethtroisi did you merge in the rotation-in-chunker code?

**Comment by sethtroisi** [comment]
I merged a "rotate chunks" script but not rotation by batch during training

**Comment by sethtroisi** [comment]
https://github.com/tensorflow/minigo/pull/278
