### ISSUE TITLE
Change Dirichlet noise to only affect legal moves

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#282]
From offline discussion:

Given the rescaling of Dirichlet when less legal moves are available there's a question of wither we should be doing that as the game progresses (e.g. after move 180 half the dirichlet noise goes to moves which are illegal)

**Comment by sethtroisi** [comment]
LZ generates a distribution that sums to 1.0 over the legal moves
https://github.com/gcp/leela-zero/blob/master/src/UCTNodeRoot.cpp#L92

MG does not do this.
If you were to sum policy+noise the value would be less than 1.0 and trend towards 0.75 (the mixing ratio) as number of legal moves heads to zero

**Comment by sethtroisi** [comment]
One possible implementation:

https://github.com/tensorflow/minigo/compare/master...sethtroisi:dirichlet

**Comment by amj** [comment]
i'd be happy to merge this in if you want to make a PR

**Comment by sethtroisi** [comment]
I have a PR but it still needs tests working on it tonight

**Comment by sethtroisi** [comment]
Fixed in
https://github.com/tensorflow/minigo/pull/299
and
https://github.com/tensorflow/minigo/pull/295
