### ISSUE TITLE
Undefined names 'good_size' and 'pi1'

### ISSUE THREAD

**Issue by cclauss** [tensorflow/minigo#317]
Undefined names can potentially raise NameError at runtime.

flake8 testing of https://github.com/tensorflow/minigo on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./oneoffs/rotate_examples.py:71:25: F821 undefined name 'good_size'
        error = (size - good_size) / (in_size + 1)
                        ^
./tests/test_preprocessing.py:136:17: F821 undefined name 'pi1'
                pi1.reshape((go.N, go.N)), pi2((go.N, go.N)))
                ^
2       F821 undefined name 'good_size'
2
```

**Comment by sethtroisi** [comment]
these look like they are my mistakes, thanks for finding them :)
