### ISSUE TITLE
some new games don't have a model in the comment

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#331]
last two moves in full/1532051140-tpu-player-deployment-675885fc6b-m85q9-13.sgf (not sure what hour sorry) don't have a model :/ other games all have 

`
C[models:gs://tensor-go-    minigo-v9-19/work_dir/model.ckpt-1
0.4999
`

`
C[models:
0.9450
E17 (1780) ==> D10 (217) ==> Q: 0.99314
move : action    Q     U     P   P-Dir    N  soft-N  p-delta  p-rel
D10  : -0.868  0.992 0.123 0.490 0.653   217 0.1220 -0.36803 -0.75
C9   : -0.870  0.974 0.105 0.134 0.178    69 0.0388 -0.09508 -0.71
A13  : -0.870  0.961 0.091 0.076 0.102    45 0.0253 -0.05118 -0.67
C15  : -0.869  0.960 0.091 0.075 0.000    44 0.0247 -0.05011 -0.67
D12  : -0.869  0.949 0.080 0.053 0.000    35 0.0197 -0.03307 -0.63
A9   : -0.871  0.938 0.068 0.034 0.046    27 0.0152 -0.01928 -0.56
F15  : -0.871  0.925 0.055 0.024 0.000    23 0.0129 -0.01092 -0.46
G19  : -0.872  0.921 0.049 0.021 0.000    22 0.0124 -0.00833 -0.40
H15  : -0.870  0.920 0.051 0.020 0.000    21 0.0118 -0.00848 -0.42
B12  : -0.873  0.913 0.041 0.016 0.000    20 0.0112 -0.00427 -0.28
A5   : -0.872  0.909 0.037 0.013 0.000    19 0.0107 -0.00263 -0.20
E8   : -0.870  0.898 0.029 0.009 0.000    17 0.0096  0.00020  0.02
A16  : -0.873  0.893 0.021 0.006 0.000    16 0.0090  0.00263  0.41
J11  : -0.869  0.890 0.021 0.006 0.000    15 0.0084  0.00238  0.39
H12  : -0.870  0.888 0.018 0.005 0.007    15 0.0084  0.00321  0.62];B[fb]C[models:
0.9982
D10 (1017) ==> Q: 0.99785
move : action    Q     U     P   P-Dir    N  soft-N  p-delta  p-rel
F18  :  1.029  0.998 0.031 0.323 0.431   435 0.4281  0.10482  0.32
E18  :  1.029  0.995 0.033 0.160 0.000   198 0.1949  0.03516  0.22
C13  :  1.029  0.994 0.035 0.129 0.171   153 0.1506  0.02191  0.17
B3   :  1.028  0.990 0.038 0.087 0.116    93 0.0915  0.00452  0.05
B13  :  1.028  0.984 0.045 0.062 0.083    57 0.0561 -0.00639 -0.10
A4   :  1.028  0.972 0.056 0.046 0.000    33 0.0325 -0.01326 -0.29
A3   :  1.029  0.966 0.062 0.042 0.056    27 0.0266 -0.01541 -0.37
O5   :  1.027  0.937 0.090 0.033 0.043    14 0.0138 -0.01874 -0.58
E10  :  1.026  0.866 0.160 0.027 0.000     6 0.0059 -0.02115 -0.78
J16  :  0.620  0.061 0.560 0.013 0.018     0 0.0000 -0.01349 -1.00
G16  :  0.577  0.061 0.516 0.012 0.017     0 0.0000 -0.01245 -1.00
B9   :  0.350  0.061 0.290 0.007 0.009     0 0.0000 -0.00699 -1.00
G11  :  0.336  0.061 0.275 0.007 0.009     0 0.0000 -0.00664 -1.00
B19  :  0.331  0.061 0.270 0.007 0.009     0 0.0000 -0.00652 -1.00
E8   :  0.264  0.061 0.204 0.005 0.000     0 0.0000 -0.00491 -1.00])
`

**Comment by tommadams** [comment]
Full path: gs://tensor-go-minigo-v9-19/sgf/full/2018-07-20-01/1532051140-tpu-player-deployment-675885fc6b-m85q9-13.sgf

**Comment by tommadams** [comment]
So I finally got a chance to look at this properly.

The `1532051140-tpu-player-deployment-675885fc6b-m85q9-13.sgf` file I found in my previous comment doesn't have contents that match what you posted (the earliest model listed is ckpt-12 not ckpt-1).

Do you have any pointers to other examples?

**Comment by sethtroisi** [comment]
I think we discovered this can only happen on the last move and likely won't be an issue soon
