### ISSUE TITLE
Reload flags from a file when creating a new MctsPlayer

### ISSUE THREAD

**Issue by tommadams** [tensorflow/minigo#335]
We'd like to be able to change some flag values dynamically while self play is still running, e.g. disable_resign_pct, resign_threshold.

We currently have to rebuild the docker image each time and perform a rolling restart of all selfplay workers. Instead, add something like a gflags flagfile that we reload every time we create a new MctsPlayer. `SetCommandLineOption` seems like it might be useful here.

**Comment by tommadams** [comment]
One wrinkle is that we'll want to read the flags file off GCS. We currently rely on tensorflow to provide GCS access because Google doesn't provide a C++ GCS client.

There's a third party [google-cloud-cpp](https://github.com/GoogleCloudPlatform/google-cloud-cpp) project but running `gsutil` as a subprocess might be simpler.

**Comment by brilee** [comment]
Yeah, I remember thinking about how I'd do a "flagfile from GCS" and basically ended up at "probably just use gsutil subprocess"

**Comment by tommadams** [comment]
Fixed by #355
