### ISSUE TITLE
Add some automatic python linting

### ISSUE THREAD

**Issue by Kashomon** [tensorflow/minigo#35]
Would help catch lots of bugs and help ensure style conformance.

**Comment by Kashomon** [comment]
Plan is to auto-run linting, formatting check, and tests on code submission. for linting, there'll be a blacklist while things are cleaned up.

**Comment by Kashomon** [comment]
I've still got more files to clean up, but this is automatic now.

**Comment by amj** [comment]
Have we got some docs on how to do this/what our project-wide flags are for autopep8?

**Comment by tommadams** [comment]
By default, autopep8 is fairly lax about whitespace and will for example allow function arguments that span multiple lines to be formatted in a bunch of different ways. This is different from something like clang-format, which enforces a one-true-way of formatting.

You can run autopep8 with two -a command line arguments to tell it to be much more aggressive about reformatting whitespace. Maybe we should consider using that?

**Comment by brilee** [comment]
I'm happy with the linter in our automated testing enforcing no style regressions and gradually adding things to be linted.
