### ISSUE TITLE
sgf logging is buggy

### ISSUE THREAD

**Issue by brilee** [tensorflow/minigo#362]
@amj @tommadams 

I've been parsing SGFs to upload to BQ. There's two things that make this tricky

1. The logging looks like this - 
models:gs://BUCKET/work_dir/model.ckpt-139529
rather than
models:gs://BUCKET/models/000001-zephyr

2. Whenever there are mixed models in a move, the first, then second model gets nulled out. (These are log rows from 4 consecutive moves in a SGF.)

```
models:gs://BUCKET/work_dir/model.ckpt-1
models:gs://BUCKET/work_dir/model.ckpt-1,gs://BUCKET/work_dir/model.ckpt-0
models:gs://BUCKET/work_dir/model.ckpt-0,gs://BUCKET/work_dir/model.ckpt-12
models:gs://BUCKET/work_dir/model.ckpt-12
```

3. Related to 2., there are some rows that are missing model numbers entirely, or only have nulled out models. (See lines 8770 - 8878 and 9058, 9076 from gs://BUCKET/sgf/full//2018-07-20-00/1532048175-tpu-player-deployment-675885fc6b-zw58c-5.sgf)
```
models:gs://BUCKET/work_dir/model.ckpt-1
models:gs://BUCKET/work_dir/model.ckpt-1,gs://BUCKET/work_dir/model.ckpt-0
models:gs://BUCKET/work_dir/model.ckpt-0
models:gs://BUCKET/work_dir/model.ckpt-0
models:gs://BUCKET/work_dir/model.ckpt-0
models:gs://BUCKET/work_dir/model.ckpt-0,gs://BUCKET/work_dir/model.ckpt-12
models:gs://BUCKET/work_dir/model.ckpt-12
```

**Comment by brilee** [comment]
I can work around these issues for now, with the caveat that our BQ data will be annotated by checkpoint # rather than model #.

**Comment by brilee** [comment]
(I'm going to upload with all the weirdness anyway, and am hoping to see if the moves played with "model-ckpt-0" are crappier than the other moves)

**Comment by amj** [comment]
2. is probably an accurate portrayal of what happened.

I bootstrapped a model and copied it into the work dir
I renamed it according to the `model.ckpt-###` name format, using '1' as the number
I start training.  The estimator code realizes that the number doesn't match global step.  It immediately exports the model at global step 0
It takes 12 training steps and re-exports it.

As this happens, all players see the first model ("...-1"), and start playing.  Then they see the new file for -0, and the new file for ...-12.

you should probably only see monotonically increasing model numbers for everything else.

**Comment by brilee** [comment]
Ah, okay, so it's just a coincidence that I happened to debug my script using the first generation of games.

**Comment by amj** [comment]
we certainly could do it, it's just more code.  i don't think we need to, though.
It's probably easier to keep track of which checkpoint got 'promoted' to which named-model, especially if we do some kind of gating in the future.

**Comment by tommadams** [comment]
I finally got a chance to look into the missing model name from 3: we don't perform any inferences on the last couple of moves before hitting the move limit, so I think this is the expected behaviour.

There's [explicit logic](https://github.com/tensorflow/minigo/blob/master/cc/mcts_player.cc#L210) in the tree search code that prevents it from looking past the move limit. And with `num_readouts=800` it's entirely possible that we don't perform any inferences for the second-to-last move either, due to tree reuse.
