### ISSUE TITLE
[CC] configue_tensorflow.sh should not delete tensorflow directory if script fails

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#368]
It takes ~2 hours for TF to compile, it's not nice to have that all thrown away because the copy fails at the very end.

**Comment by tommadams** [comment]
We should probably just remove that `rm -rf` from the script altogether.

**Comment by sethtroisi** [comment]
the temp folder is still deleted 
https://github.com/tensorflow/minigo/blob/master/cc/configure_tensorflow.sh#L10

**Comment by tommadams** [comment]
Well yes, the configuration & build process writes a bunch of stuff into unknown locations in the tmp_dir. If you don't delete them, parts of the install process will fail. One step that I remember off the top of my head is here: https://github.com/tensorflow/minigo/blob/d50b7a56e8b24286072ed8389843a843f886ca0c/cc/configure_tensorflow.sh#L60

My assumption was that if you were trying to continue from a failed install, you'd comment out the earlier steps. In general, I don't think it's wise to attempt to make the configure script be magically resumable from any point.
