### ISSUE TITLE
gogui says we played illegal move?

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#370]
![screenshot from 2018-08-11 02-46-03](https://user-images.githubusercontent.com/10172976/43990445-cf7ab144-9d10-11e8-9ed9-92aa68e3c178.png)

SGF:
(;FF[4]CA[UTF-8]AP[GoGui:1.4.9]
KM[6.5]PB[gogui-twogtp]PW[gogui-twogtp]DT[2018-08-11]
;B[pd];W[dd];B[pp];W[dp];B[pj];W[qq];B[qp];W[pq];B[oq];W[or]
;B[nq];W[nr];B[mq];W[qc];B[qd];W[pc];B[oc];W[ob];B[nc];W[nb]
;B[mc];W[mb];B[cn];W[lc];B[ne];W[mr];B[ck];W[lq];B[no];W[cf]
;B[fq];W[dn];B[cm];W[eq];B[fp];W[co];B[fc];W[db];B[ic];W[fr]
;B[gr];W[er];B[hq];W[ci];B[ek];W[mj];B[nh];W[kj];B[nm];W[rd]
;B[re];W[rc];B[qf];W[rp];B[ro];W[rq];B[qn];W[mh];B[bn];W[bo]
;B[eb];W[ec];B[fb];W[fd];B[gd];W[fe];B[ei];W[ge];B[cb];W[da]
;B[hd];W[ni];B[oh];W[cg];B[nk];W[ij];B[if];W[ih];B[fg];W[gg]
;B[hg];W[gh];B[hh];W[hi];B[gf];W[ff];B[gi];W[hf];B[ig];W[jh]
;B[fh];W[gf];B[he];W[gj];B[fi];W[cc];B[gl];W[mg];B[ao];W[ap]
;B[an];W[bq];B[bj];W[bi];B[jq];W[kq];B[jp];W[jl];B[kr];W[lr]
;B[jr];W[kb];B[hk];W[hj];B[im];W[jm];B[in];W[en];B[fj];W[gk]
;B[fk];W[hl];B[hm];W[il];B[fm];W[nf];B[of];W[me];B[ai];W[oe]
;B[nd];W[md];B[od];W[og];B[pe];W[oi];B[pg];W[ph];B[qh];W[pi]
;B[qi];W[mk];B[ag];W[be];B[ef];W[eg];B[dg];W[ee];B[df];W[de]
;B[dh];W[bh];B[ah];W[af];B[bg];W[bf];B[aj];W[ch];B[ml];W[ll]
;B[lm];W[km];B[ln];W[ok];B[oj];W[nj];B[nl];W[qj];B[pk];W[je]
;B[hb];W[ie];B[gc];W[jc];B[ga];W[id];B[jb];W[ja];B[ib];W[ka]
;B[fn];W[eo];B[di];W[cj];B[bl];W[dj];B[fo];W[ep];B[dk];W[em]
;B[ls];W[ms];B[ks];W[lo];B[kp];W[lp];B[kn];W[ar];B[jn];W[el]
;B[fl];W[fs];B[mo];W[gs];B[hs];W[ko];B[jo];W[mp];B[np];W[sp]
;B[so];W[pr];B[sd];W[sc];B[se];W[ia];B[dl];W[ea];B[ha];W[fa]
;B[dm];W[ej])

**Comment by amj** [comment]
this needs more context; was this loading an SGF?  was this a 1v1 match via go-gui?  how was this executed?

**Comment by sethtroisi** [comment]
I ran the code fragment in the README.md

```
BLACK="gnugo --mode gtp"
WHITE="python3 gtp.py --load_file=path/to/model"
TWOGTP="gogui-twogtp -black \"$BLACK\" -white \"$WHITE\" -games 10 \
  -size 19 -alternate -sgffile gnugo"
gogui -size 19 -program "$TWOGTP" -computer-both -auto
```

**Comment by amj** [comment]
hey @tommadams we have superko now, is this a thing of the past?

**Comment by tommadams** [comment]
Well superko is only implemented in C++ and Seth ran `gtp.py`, so... no.

Do we care enough to implement superko in Python?
