### ISSUE TITLE
[Feature Request] Support undo in GTP

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#374]
It's a very nice feature when reviewing / playing against bot

**Comment by brilee** [comment]
FWIW, KGS implements "undo" by issuing clearboard and replaying the game history up to move N-1, and minigo's GTP handler should just work out of the box for this purpose.

**Comment by amj** [comment]
@brilee that does work in KGS today, but as we start thinking about ways to make minigui more useful, supporting undo can be better than 'clear & replay' as you can to keep your tree stats.

**Comment by tommadams** [comment]
I added an `undo` GTP command a while back for Minigui.
