### ISSUE TITLE
how to deal with Residue and Double live？result is correct?

### ISSUE THREAD

**Issue by fmscole** [tensorflow/minigo#401]
def score(self):
        'Return score from B perspective. If W is winning, score is negative.'
        working_board = np.copy(self.board)
        while EMPTY in working_board:
            unassigned_spaces = np.where(working_board == EMPTY)
            c = unassigned_spaces[0][0], unassigned_spaces[1][0]
            territory, borders = find_reached(working_board, c)
            border_colors = set(working_board[b] for b in borders)
            X_border = BLACK in border_colors
            O_border = WHITE in border_colors
            if X_border and not O_border:
                territory_color = BLACK
            elif O_border and not X_border:
                territory_color = WHITE
            else:
                territory_color = UNKNOWN  # dame, or seki
            place_stones(working_board, territory_color, territory)

        return np.count_nonzero(working_board == BLACK) - np.count_nonzero(working_board == WHITE) - self.komi
#############################################################################
Looking at this code, I feel there is no distinction between Residue and Double Live, the remnants are regarded as double live, so it seems very problematic to calculate the winning or losing?

How to deal with it?

看了这个代码，感觉残子（Residue）和双活（Double live）并没有区分，残子都当成了双活，这样计算胜负似乎很有问题啊？
该怎么处理呢？
一方连续pass两次就结束，留有残子的一方显然划算。

**Comment by brilee** [comment]
This method scores according to Tromp-Taylor scoring, which in theory is almost exactly the same as Chinese counting style. I think what you mean by "Residue" is https://senseis.xmp.net/?Dame and "double live" is https://senseis.xmp.net/?Seki . So for dame, they are counted as nobody's territory - Chinese ruleset games should not end until both players have completely filled in all dame. Seki is handled according to however many stones can be added to the position until it is stable.

**Comment by fmscole** [comment]
@brilee 

thank you very much!
I am English very poor, I speak Chinglish  ^_^
yes, I mean that "double live" is Seki .
