### ISSUE TITLE
Missing training data

### ISSUE THREAD

**Issue by IsmailMamoru** [tensorflow/minigo#406]
Hello everyone, 
i'm having a problem with the missing data:
when i run the following training command i get an error which says the number of steps is 0:
BOARD_SIZE=19 python3 main.py train-dir \
  gs://$BUCKET_NAME/data/training_chunks \
  gs://$BUCKET_NAME/models/000001-somename \
  --model_dir estimator_working_dir

after reading many part of the code i found that with this call 

dual_net.train(training_file) #line 92 rl_loop.py

the default value of steps is -1
and in dual_net.py : 
if steps == -1:
       #some code here then
       steps = total_examples // effective_batch_size

going further : 
with gsutil ls gs://$BUCKET_NAME, there is no data folder or file:

gs://minigo-pub/v9-19x19/models/
gs://minigo-pub/v9-19x19/sgf/

does any one know how can i get the data

**Comment by brilee** [comment]
I've started copying over the ~500GB of training chunk data to gs://minigo-pub/v9-19x19/data/golden_chunks. Should be done in a few minutes.

**Comment by IsmailMamoru** [comment]
Thank you @brilee, that was hopeful

**Comment by fmscole** [comment]
@brilee
Where can I get your data in China? Such as BaiduNetDisk. Because GS can not be used in China.Thank you.

**Comment by brilee** [comment]
Ah.. that's unfortunate. I don't know anything about the Chinese tech ecosystem so I'm afraid I can't help you out there.
