### ISSUE TITLE
Training Epoch uses all the GPU memory

### ISSUE THREAD

**Issue by IsmailMamoru** [tensorflow/minigo#407]
Hello eveyone, 
Running the following command :
BOARD_SIZE=19 python3 main.py train-dir ./data ./minigo-models/000001-zephyr --model_dir estimator_working_dir

would show memory allocation problem.

First i thought about data size as source of the problem, so i limited myself to a subset with 172 mb.

then i tried other models , same problem

i have a 8GB gpu, and here what nvidia-smi shows :
=====================================================
| Processes:                                                               GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
=====================================================
...
|    0     xxxxxx      C        python3                                     7803MiB   |

**Comment by fmscole** [comment]
I  think  that   'train_batch_size'   should  be set    156:
flags.DEFINE_integer('train_batch_size', 156,
                     'Batch size to use for train/eval evaluation. For GPU '
                     'this is batch size as expected. If \"use_tpu\" is set,'
                     'final batch size will be = train_batch_size * num_tpu_cores')

**Comment by brilee** [comment]
FYI - The way the absl.flags library works is that you can pass in `--train_batch_size=156` in the command line flags and it will override the default value set in the code.

**Comment by IsmailMamoru** [comment]
The train_batch_size variable is already defined dual_net.py , i had to change it to 16 and it used 7.8 GB

**Comment by fmscole** [comment]
@IsmailMamoru 
I means that  'train_batch_size' be set such as 156 or 100  from 256 . 
by  pass in --train_batch_size=156 in the command line flags  or change it in code .

**Comment by bluecryolite** [comment]
yes, it works after I set train_batch_size to 156. thanks.
