### ISSUE TITLE
Create evaluation server

### ISSUE THREAD

**Issue by brilee** [tensorflow/minigo#44]
We should have a zoo where self-play variants can play against each other to establish ratings. This could just mean figuring out the infrastructure to automatically hook new training checkpoints into CGOS, ideally without overwhelming CGOS.

**Comment by amj** [comment]
@brilee we can probably play these games faster not on CGOS, right?   I'd love to see us hash out (maybe on this issue?) some more concrete requirements here are viz latency, quantity, params/readouts, etc.

**Comment by brilee** [comment]
I would expect that we could play games faster, maybe because we wouldn't have to wait for slower games to complete. But then again, I think the CGOS behavior is the correct behavior, because otherwise you get into dynamics where "players that tend to finish their games fast" keep on getting rematched with each other. So it's important to let all games complete and then do a completely random repairing. CGOS is correct in this regard.

I don't really have a sense for how much stronger our players get with #readouts; unclear to me what the right tournament settings are. My first guess would just be identical to self play conditions (constant # of readouts per move for each side).

**Comment by amj** [comment]
@brilee so are you leaning towards running our own CGOS internally, or towards automatically putting checkpoints on CGOS for N games?

**Comment by amj** [comment]
Closed, we've got our eval jobs on a cluster -- no external bots right now but it's still pretty good.
