### ISSUE TITLE
Question regarding commented self-play games on cloudygo

### ISSUE THREAD

**Issue by barrtgt** [tensorflow/minigo#466]
Why doesn't the move that gets picked show up on the top all of the time? Aren't they sorted by nodes?

**Comment by brilee** [comment]
For the first 30 moves, moves are softpicked from the visit distribution for game variety - can lead to picking a move that's not the top choice.

**Comment by barrtgt** [comment]
Yes that explains it. Thanks. Just trying to figure this out. Is it right to believe that for a search with 99 simulations for one move and 1 simulation for another, the move with 1 simulation would get picked 1% of the time in this situation?

**Comment by brilee** [comment]
Yes. Although I think at some point we experimented with squashing the
probabilities to make unlikely moves slightly more likely.

**Comment by barrtgt** [comment]
Would squashing have a different effect than changing cpuct?

**Comment by brilee** [comment]
Good question - I think you’re right that they would both have a similar
effect, although they’d differ in the exact shaping.
