### ISSUE TITLE
minigo/cc: ImportError: No module named proto

### ISSUE THREAD

**Issue by delock** [tensorflow/minigo#489]
I'm trying to run the cc version of minigo.  As I follow the steps in https://github.com/tensorflow/minigo/tree/master/cc, I get the following error when I tried to launch the binary for selfplay.
I had set PYTHONPATH properly (see below) and direct import from python command is working, what might cause failure to import when executing bazel-bin/cc/main?

```
~/minigo$ ./bazel-bin/cc/main --model=~/results/minigo/final/000004-noted-earwig-puzzles.txt --mode=selfplay                                                                                                               
Inference server listening on port 50051
MctsPlayer options: name:minigo inject_noise:1 soft_pick:1 random_symmetry:1 resign_threshold:-0.999 resign_enabled:1 batch_size:8 komi:7.5 num_readouts:100 seconds_per_move:0 time_limit:0 decay_factor:0.98 random_seed:0                   
Random seed used: 1538990222978319
Traceback (most recent call last):
  File "inference_worker.py", line 31, in <module>
    from proto import inference_service_pb2
ImportError: No module named proto

^C
~/minigo$ python3
Python 3.4.5 (default, Dec 11 2017, 14:22:24)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from proto import inference_service_pb2
>>> quit()
~/minigo$ echo $PYTHONPATH
/home/gma/minigo
~/minigo$ 

```

**Comment by amj** [comment]
can you verify that `which python` indeed is the python in your virtualenv?  e.g. for me it is `$HOME/.virtualenvs/minigo/bin/python`

If you haven't set up a virtualenv (and don't want to), you can install all the python dependencies by running `pip install -r requirements.txt` (or `pip3` if you also have python2 on your system)

Alternatively, you could just `pip3 install protobuf`

**Comment by delock** [comment]
I guess its my environment and will try it on another machine, close for now.

**Comment by sethtroisi** [comment]
I had a similiar problem in  https://github.com/tensorflow/minigo/issues/441 I fixed it by remembering to activate my virtual env
