### ISSUE TITLE
python3 not python and also not sure how to do it locally

### ISSUE THREAD

**Issue by kwccoin** [tensorflow/minigo#51]
In the readme.md
   python rl_loop.py selfplay --readouts=$READOUTS -v 2
should be
    python3 rl_loop.py selfplay --readouts=$READOUTS -v 2

Still not sure how to do it using local file

**Comment by amj** [comment]
if you're in an active virtualenv, running `which python` should show you that venv's python, and `python --version` should be python 3.x

think of rl_loop.py as a bunch of shortcuts for running main.py with the settings used for a large cluster -- probably better to run `main.py` when running locally

**Comment by Kashomon** [comment]
Going to close this since the instructions say to use virtualenv. please reopen if that doesn't work for you.

**Comment by kwccoin** [comment]
Thanks.  Still trying to explore as a programmer and Go player.
