### ISSUE TITLE
cc build error - libgrpc_runtime.so missing

### ISSUE THREAD

**Issue by MartinRe63** [tensorflow/minigo#538]
I got the same issue as documented here: 

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/tensorflow_minigo/512/pull-tf-minigo-cc/384/build-log.txt

ERROR: missing input file '//cc:tensorflow/libgrpc_runtime.so'

when I tried to build the c++ version. Also in GRPC github nor in tensorflow a lib like this is visible. How to build this lib?

**Comment by tommadams** [comment]
You will need to rerun `//cc/configure_tensorflow.sh', it was recently updated to build that library: https://github.com/tensorflow/minigo/commit/10410035dd2d73d153648dfc79c4d3e4e43ebd05#diff-dc0a2c249773d31d3d4755f00de5892d

Please reopen this issue if that doesn't fix your problem.

**Comment by MartinRe63** [comment]
yes. correct. thx. after a bazel update to 18.1 and running configure_tensorflow.sh the lib is available.
