### ISSUE TITLE
Add custom compiling of TensorFlow for CPU Image

### ISSUE THREAD

**Issue by Kashomon** [tensorflow/minigo#58]
We should add custom compiling of TensorFlow for the CPU Image[s]. The problem is that the default CPU pip package is not optimized. Compiling from source can give a 30% CPU-usage boost.

**Comment by Kashomon** [comment]
We accidentally ripped this out in this PR: https://github.com/tensorflow/minigo/commit/b32a4724dd2f8c97ff3b3813e5622d6bb6fb8f7a#diff-447aae5289185e65a89c12f6bb0011ef

**Comment by amj** [comment]
i've got this working again in #68 , will merge and send for review tomorrow.

**Comment by amj** [comment]
Fixed by #68
