### ISSUE TITLE
sgf parser explosion

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#587]
i don't have a callstack handy as i was using Seth's box.
But i was using [this sgf](https://pandanet-igs.com/system/sgfs/8031/original/AQEYAWDNSF.sgf?1543413330)

from [this page](https://pandanet-igs.com/communities/agacityleague/rounds/518)

**Comment by sethtroisi** [comment]
At the end of the file it contains

```
; TW[.....]
TB[....]

OS[...])
```

it's possible this parses as an empty sequence and that's invalid.

**Comment by sethtroisi** [comment]
SGF also contains three passes but IDK.
