### ISSUE TITLE
Pass around saved/exported models everywhere

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#60]
instead of having our selfplay workers constantly look for the `.data-00000-of-00001, .index, .meta` files, we should properly export our graph.  Not only would this make a lot of our scripts cleaner, it'd be a good way to run some optimizers etc. prior to farming it all out.

**Comment by killerducky** [comment]
Running an optimizer, is that like tensorrt? The leela-chess guys had some great results with that.

**Comment by amj** [comment]
I hadn't heard of that -- i was pointed towards [toco](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/toco) .  I'll go look up tensorrt

**Comment by killerducky** [comment]
leela-chess benchmarks:
https://github.com/glinscott/leela-chess/issues/52#issuecomment-362252598

Looks like they are working on integrating into TF:
https://github.com/tensorflow/tensorflow/pull/16253

**Comment by amj** [comment]
Yes, that's it almost exactly.   `out_graph = tf.graph_util.convert_variables_to_constants(n.sess, n.sess.graph.as_graph_def(), ["policy_output", "value_output"])`

**Comment by Error323** [comment]
Hi,

Indeed, TensorRT seems very promising, unfortunately as of now you won't be able to export your tensorflow network to `uff` format for importing as the Merge operator is unsupported. This leaves three possibilities:

- Create a network clone in TensorRT using their [C++ API](http://docs.nvidia.com/deeplearning/sdk/tensorrt-api/index.html) and use exported weights from tensorflow
- Wait for TensorRT to support tensorflow 1.4 and beyond
- Wait for the PR mentioned above to be merged

The PR probably makes the most sense. Nice project! (offtopic: @amj it looks like you're from the AlphaGo documentary, awesome!)

**Comment by amj** [comment]
@Error323 thanks for the great summary, much appreciated!  We'll check it out.  I think it's a pretty open space w.r.t. what sort of optimizations are possible so we might not lock in to TensorRT immediately.  (I am the guy from doc, yep -- had to study up on NNs since then ;)  I'm really watching the leela chess project with great interest!

**Comment by brilee** [comment]
I think we've done this in the course of implementing C++ selfplay?
