### ISSUE TITLE
nan in sgf file

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#666]
![screenshot from 2019-01-26 18-34-25](https://user-images.githubusercontent.com/10172976/51795497-16ef3880-2199-11e9-9345-ef71c27edbd5.png)

v16-19x19/sgf/full/2019-01-26-12/1548507349-tpu-player-deployment-d74dbc759-cdckf-5.sgf

**Comment by amj** [comment]
we may have found a bad box; one machine in particular has been spewing nans and we haven't tracked it down yet.  @gitosaurus FYI

**Comment by sethtroisi** [comment]
I'm still seeing these happen

1549516944-tpu-player-deployment-d74dbc759-r54s2-15.sgf

/sgf/full/2019-02-07-05/1549516944-tpu-player-deployment-d74dbc759-r54s2-15.sgf

**Comment by sethtroisi** [comment]
Both of these pods **r54s2** and **6bqkm** have a dozen or so games with NaNs

**Comment by amj** [comment]
v16?

**Comment by sethtroisi** [comment]
yes
