### ISSUE TITLE
Why are there two kind of Minigo v15-990 Models Converted?

### ISSUE THREAD

**Issue by atoutw** [tensorflow/minigo#669]
I downloaded ***_quantized's weight from the link below.

http://www.flygo.net/bbs/forum.php?mod=viewthread&tid=108919&extra=page%3D1&page=1

But that is just different from the weight downloaded from the link below.

https://cloudygo.com/converted_model/v15-19x19/models/

![image](https://user-images.githubusercontent.com/43053753/52023730-a0a85880-2541-11e9-9694-8eef0c26ab4a.png)
![image](https://user-images.githubusercontent.com/43053753/52024088-d437b280-2542-11e9-87ff-b07ce76ae3a0.png)

**Comment by sethtroisi** [comment]
The CloudyGo version is quarantined with 6 digits.

the v15-19x19 quantized file comes from the [colab ](https://colab.research.google.com/drive/16eXKg_WswzadfpfbIZzATcSy0qL7F0gC#scrollTo=dUxJFs8HW8WC) which is quantized to 3 digits which can changes it's play

Run I run the code lab it says 
"Weight file difference L2-norm: 0.005233"

**Comment by sethtroisi** [comment]
It's quite interesting to see the differences (not considering H16) but not unexpected given the change to the weights.

**Comment by alreadydone** [comment]
The policy probabilities can depend heavily on the symmetry chosen. To make sure it's not the effect of symmetry, run the same weight file multiple times to see if the result is consistent, or use `heatmap all` to check this position with the two weight files and compare one by one.

**Comment by atoutw** [comment]
I did some tests there.
https://github.com/gcp/leela-zero/issues/2179#issuecomment-459413040
