### ISSUE TITLE
did you test the orignal minigo engine vs leelaz+ converted weight

### ISSUE THREAD

**Issue by l1t1** [tensorflow/minigo#671]
if they run with same parameter,
whose wintate is higher, or there was no difference.

**Comment by amj** [comment]
yes, we did.  The winrate was 50-50.  @sethtroisi to confirm & close.

**Comment by sethtroisi** [comment]
Yes! I verified that our MCTS are the same in "theory" (given the same cpuct, fpu, thread=1, ...) https://github.com/tensorflow/minigo/issues/432

In practice leela has very different parameters (FPU != value-init-penalty, puct is higher, batching is very different) but they seem comparable (or better).

**Comment by sethtroisi** [comment]
@l1t1 I suspect that minigo does not support pypy3 and it wouldn't really be useful (most of our time is spent in tensorflow on running the NN)

We have a c++ engine which is what we use when we want to go as fast as possible.

**Comment by l1t1** [comment]
can you release the windows exe version, thanks

**Comment by amj** [comment]
we don't have a windows exe version at this time, sorry.

**Comment by l1t1** [comment]
thanks

**Comment by amj** [comment]
@l1t1 see also https://github.com/tensorflow/minigo/issues/77 and #580 .

**Comment by l1t1** [comment]
thanks, it seems those posts discussing python version, i mean the compiled cpp version.
