### ISSUE TITLE
what is the meaning of data in minigo sgf

### ISSUE THREAD

**Issue by l1t1** [tensorflow/minigo#678]
I copied the sgf file from 
https://cloudygo.com/v16-19x19/665/eval/2019-02-02/1549093176-minigo-cc-evaluator-665-778-bw-9hhxq-0-000665-diligent-000778-achilles.sgf?type=eval
question 
1. whats the meaning of 212 in "==>R17 (212)"
2. whats the meaning of -0.15039 in "==> Q: -0.15039"
3. whats the meaning of  "action    Q     U     P   P-Dir    N  soft-N  p-delta  p-rel" fields
4. whats the meaning of invalid (801)
5. Resign Threshold: -0.8 
-0.2097
```
(;GM[1]FF[4]CA[UTF-8]AP[Minigo_sgfgenerator]RU[Chinese]
SZ[19]KM[7.5]PW[000778-achilles]PB[000665-diligent]RE[B+R]
;B[qc]C[Resign Threshold: -0.8
-0.2097
invalid (801) ==> R17 (212) ==> D17 (111) ==> D15 (109) ==> C15 (104) ==> C14 (103) ==> C16 (102) ==> D14 (101) ==> F17 (100) ==> D4 (99) ==> Q4 (66) ==> O3 (63) ==> M3 (31) ==> G3 (11) ==> R6 (8) ==> O5 (7) ==> M5 (4) ==> Q7 (3) ==> R7 (2) ==> Q: -0.15039
move : action    Q     U     P   P-Dir    N  soft-N  p-delta  p-rel
R17  : -0.170 -0.200 0.031 0.240 0.240   212 0.2650  0.02502  0.10
C17  : -0.175 -0.208 0.034 0.241 0.241   194 0.2425  0.00148  0.01
R3   : -0.171 -0.208 0.037 0.242 0.242   179 0.2237 -0.01866 -0.08
C3   : -0.168 -0.211 0.042 0.239 0.239   153 0.1912 -0.04761 -0.20
D4   : -0.184 -0.188 0.004 0.000 0.000     2 0.0025  0.00206  4.72
Q16  : -0.186 -0.190 0.004 0.000 0.000     2 0.0025  0.00207  4.78
Q4   : -0.192 -0.196 0.003 0.000 0.000     2 0.0025  0.00213  5.72
D16  : -0.195 -0.200 0.004 0.000 0.000     2 0.0025  0.00204  4.39
R16  : -0.204 -0.207 0.003 0.000 0.000     2 0.0025  0.00220  7.29
D17  : -0.205 -0.207 0.002 0.000 0.000     2 0.0025  0.00223  8.31
Q3   : -0.206 -0.208 0.003 0.000 0.000     2 0.0025  0.00222  7.96
C4   : -0.206 -0.209 0.003 0.000 0.000     2 0.0025  0.00218  6.90
R4   : -0.221 -0.223 0.003 0.000 0.000     2 0.0025  0.00221  7.62
Q17  : -0.223 -0.226 0.003 0.000 0.000     2 0.0025  0.00221  7.77
C16  : -0.227 -0.229 0.003 0.000 0.000     2 0.0025  0.00222  7.83];
```

**Comment by sethtroisi** [comment]
1. 212 is the number of visits that move got
2. Q is our evaluation of the game -1 is white win, 1 is black win. LZ calls this "winrate"
3. Q is represents chance of winning (-1 to 1), P is policy, P-dir is Policy with dirchlet noise. N is visits, soft-N is N / total_visits ^ temperature, p-delta is how training will try to change the policy of that move
4. invalid (801) is the number of visits under the root move (the first move we call invalid)
5. We'll resign if abs(Q) > 0.8, and Q is currently -0.21 (e.g slightly better for white)

**Comment by l1t1** [comment]
@sethtroisi thank a lot
