### ISSUE TITLE
where to download the latest minigo v16 weight files ?

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#680]

**Comment by l1t1** [comment]
https://github.com/leela-zero/leela-zero/issues/2183#issuecomment-459962389

**Comment by 1-punchMan** [comment]
The updates on
[https://console.cloud.google.com/storage/browser/minigo-pub/v16-19x19/models/](https://console.cloud.google.com/storage/browser/minigo-pub/v16-19x19/models/)
seems stop?

**Comment by sethtroisi** [comment]
We push updates manually. I repushed models this morning so everything up to ~950 should be synced

**Comment by WhiteHalmos** [comment]
Thank you Seth!
