### ISSUE TITLE
Help: minigui can't work because "can't open file 'main.py'"

### ISSUE THREAD

**Issue by zliu1022** [tensorflow/minigo#681]
Hi, sir, 
Thank you first, your great effort let me see the amazing AI go.

I wish to run minigo with minigui on google cloud.
I can run minigo with below command, it work well with the gtp command, just like 'genmove b'
```
cd $HOME/github/minigo/
READOUTS=2
LATEST_MODEL=~/minigo-models/models/000990-cormorant
BOARD_SIZE=19 python3 gtp.py --load_file=$LATEST_MODEL --num_readouts=$READOUTS --verbose=3
```

So I try to run ```./minigui/fetch-and-run.sh``` , but failed.
```
Using: the following options for Minigui launch:
--------------------------------------------------
MINIGUI_PYTHON:       python3
MINIGUI_BUCKET_NAME:  minigo-pub
MINIGUI_GCS_DIR:      v15-19x19/models
MINIGUI_MODEL:        000990-cormorant
MINIGUI_MODEL_TMPDIR: /tmp/minigo-models
MINIGUI_BOARD_SIZE:   19
MINIGUI_PORT:         5001
MINIGUI_HOST:         127.0.0.1
Python Version:       Python 3.6.7

Downloading Model files:
--------------------------------------------------
Checking for: /tmp/minigo-models/000990-cormorant.data-00000-of-00001
Checking for: /tmp/minigo-models/000990-cormorant.index
Checking for: /tmp/minigo-models/000990-cormorant.meta

Freezing model
--------------------------------------------------
python3: can't open file 'main.py': [Errno 2] No such file or directory
```

Can you help me to figure it out?

Thank you.

**Comment by tommadams** [comment]
Sorry about that, it looks like `./minigui/fetch-and-run.sh` is out of date: `main.py` was broken in to separate binaries a while ago.

I'm currently working on PR #675, which changes some more Minigui stuff. Once that's pushed, I'll look into fixing this.

**Comment by tommadams** [comment]
I've updated `fetch-and-run.sh`. The configuration that it runs Minigui in will support the "demo", "lightweight demo" and "kiosk" modes, which are selectable by visiting `localhost:5001` after `fetch-and-run.sh` starts the Minigui sever. `fetch-and-run.sh` runs the Python engine, and we primarily use the C++ engine these days.

Issue #689 tracks adding support for Minigui's study mode to the Python engine.

**Comment by amj** [comment]
@zliu1022 if you finished compiling minigo, congratulations!   You might be the first one not on the team who's done so :)

from my bash history, here's how i have run it:

from the minigo/ directory, with the virtualenv activated:
```
python minigui/serve.py --model=gs://minigo-pub/v15-19x19/models/000990-cormorant.pb --engine=tf
```
and then can open it at 127.0.0.1:5001

**Comment by tommadams** [comment]
Sorry, my bad. I'll fix the documentation as soon as I have a chance.

Andrew's command line is also out of date (I've been making a lot of changes to Minigui recently).

If you've built the C++ engine (specifically the `cc:gtp` BUILD target), you can run:

```
python3  minigui/serve.py  --control=minigui/control/minigo_tf.ctl
```

You may need to edit the `minigui/control/minigo_tf.ctl` control file to load the correct model, change the number of reads per move, etc. The `.ctl` control file describes how to the Minigui server should run the engine and is similar to [gomill](https://mjw.woodcraft.me.uk/gomill/doc/0.8.2/) if you're familiar with that.

**Comment by zliu1022** [comment]
Hi, Thank you all for your warm help.

I've updated the latest script and tried below command:
```
cd $HOME/github/minigo/

export MINIGUI_BUCKET_NAME=minigo-pub
export MINIGUI_GCS_DIR=v15-19x19/models
export MINIGUI_MODEL=000990-cormorant
export MINIGUI_MODEL_TMPDIR=$HOME/minigo-models/models
export MINIGUI_TMPDIR=$HOME/minigo-models/
export MINIGUI_BOARD_SIZE=19

./minigui/fetch-and-run.sh

```

The result show below:
![image](https://user-images.githubusercontent.com/3665494/52275213-d5753f00-2989-11e9-9b74-f6244f611507.png)
Is it right?

Because I install minigo in google cloud compute engine. So I visit ```externalIP:5001``` in my chrome, but no response. I am sure I open all port of firewall.

So I try the command 'wget 127.0.0.1:5001' and have got the index.html.
![image](https://user-images.githubusercontent.com/3665494/52275712-4701bd00-298b-11e9-89ec-73ea06a71538.png)

Is it possible for me to connect minigo using external IP address? @tommadams

**Comment by zliu1022** [comment]
Hi, @tommadams 

I tried your command ```python3 minigui/serve.py --control=minigui/control/minigo_tf.ctl ```

Got this result below:
![image](https://user-images.githubusercontent.com/3665494/52278299-afec3380-2991-11e9-8dc9-a141a4c2e123.png)

But still can't visit "external IP:5001" with chrome, and ```wget 127.0.0.1:5001``` also succeed.

Could you take some time help me again? I really appreciate your help.

By the way, I have my own [Webgo](https://github.com/zliu1022/webgo) which is also installed on google cloud compute engine to use leelazero , so I can visit through external IP with my mobile phone browser. Webgo use one port to show static web page and another port using websocket to transfer leelazero analyze information.

**Comment by zliu1022** [comment]
Sorry, forgive my carelessness. I check the code, it works now with external IP :5001.
![image](https://user-images.githubusercontent.com/3665494/52279326-491c4980-2994-11e9-8de0-e42d1e7ff1e9.png)

If I have any other question, I will go back to you.
Thank you:-)

**Comment by amj** [comment]
nice work!  Let us know how things go!
