### ISSUE TITLE
ImportError: cannot import name 'bigtable'

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#682]
after I git clone mining ,and tried to run self play.py on local tensor flow env of my Mac,
i got below error:

(tensorflow) bash-3.2$ python3 selfplay.py --verbose=2 --num_readouts=400 --load_file=./models/000798-golden-lion
Traceback (most recent call last):
File "selfplay.py", line 29, in 
import preprocessing
File "/Users/chunmwan/Downloads/minigo/preprocessing.py", line 19, in 
import bigtable_input
File "/Users/chunmwan/Downloads/minigo/bigtable_input.py", line 29, in 
from google.cloud import bigtable
ImportError: cannot import name 'bigtable'
(tensorflow) bash-3.2$ python
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

from google.cloud import bigtable
Traceback (most recent call last):
File "", line 1, in 
ImportError: cannot import name 'bigtable'
who knows how to resolve this issue ?

Thanks

**Comment by brilee** [comment]
Hi, have you run `pip install -r requirements.txt` in your virtualenv? google.cloud.bigtable is one of the listed dependencies and it seems like that's what your missing.

**Comment by amj** [comment]
closing, feel free to reopen if this does not solve your problem.
