### ISSUE TITLE
20b vs 40b at time parity

### ISSUE THREAD

**Issue by WhiteHalmos** [tensorflow/minigo#697]
```
v15m990__10s v v16m930__10s (100/1000 games)
board size: 19   komi: 7.5
               wins              black         white       avg cpu
v15m990__10s     62 62.00%       30 60.00%     32 64.00%    501.39
v16m930__10s     38 38.00%       18 36.00%     20 40.00%    525.92
                                 48 48.00%     52 52.00%
```

<details>
<summary>gomill control</summary>

```
competition_type = 'playoff'
#Run: c/05
p1, p2, g1 = 'v15m990__10s', 'v16m930__10s', 1000
pa = [p1]
pb = [p2]
gn = [g1]
board_size, komi = 19, 7.5
def LZ(vals):
  commands = ['time_settings 0 11 1']
  A = '../leelaz --noponder -g -t1 -d -w w/{} --precision half --timemanage fast {}'
  return Player(A.format(*vals), startup_gtp_commands=commands)
players = {a: LZ(a.split('_')) for a in pa + pb}
matchups = [Matchup(a, b, alternating=True, number_of_games=g)
            for a, b, g in zip(pa, pb, gn)
```
</details>

**Comment by WhiteHalmos** [comment]
Not enough games yet to tell, but perhaps the 40b net needs more games to reach the same strength as 20b, but has a higher ceiling?

Around 85 n/s for 40b and 180 n/s for 20b, which results in 600-800 visits for 40b vs 1600-1800 visits for 20b.

**Comment by sethtroisi** [comment]
Thanks for running these games.
They are matching my personal results which suggest v16 isn't as strong as v15 even without time parity

**Comment by l1t1** [comment]
@bjiyxo use net2net to build lz 20b from lz 6b , 
https://github.com/leela-zero/leela-zero/issues/1113
but 40b from Xavier Initialization
https://github.com/leela-zero/leela-zero/issues/1681#issuecomment-409949202

**Comment by WhiteHalmos** [comment]
ELO difference of
