### ISSUE TITLE
TPU pods die after ~7d

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#702]
After a long time, our TPU selfplay jobs hang with no logs.  I thought i saw something about memory fragmentation on the TPU causing Session::Run to hang, but of course i can't find it again.  

It'd be nice to track down what's happening.

Possibly the first step would be to do some kind of a watchdog thread that gets pet at game completion: If no games have been completed within an hour or something, terminate and leave a message.

**Comment by sethtroisi** [comment]
Closing old issues.
