### ISSUE TITLE
implement progressive widening per paper

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#706]
Now that we're interested in high-playout games, we should adjust the U term to grow with N.

**Comment by l1t1** [comment]
I read from https://cloudygo.com/v17-19x19/models/
it generate a new weight about 30m, each weight played about 25000 games, just similar as v16
i wonder why high-playout games didnt cost more time.

**Comment by amj** [comment]
none of these are high-playout games, so i'm not sure what you're asking.

If you're asking why the rate of new models is slower, a couple reasons:
- the models at the start of a run play more moves per game on average, because it hasn't figured out how to resign
- we also have ~100 TPUs less for v17.

**Comment by l1t1** [comment]
thanks
I thought new models should be slower, as they high-playout games.
since you said none of them are high-playout games, so i understand
