### ISSUE TITLE
error：v15-19x19/001144-two-lions

### ISSUE THREAD

**Issue by ivysrono** [tensorflow/minigo#710]
https://cloudygo.com/all-eval-graphs

![default](https://user-images.githubusercontent.com/2649544/52615740-2e386080-2ed1-11e9-973a-b0002a8baba8.png)

it should be v16

**Comment by sethtroisi** [comment]
Thanks, I'll look into what happened.

**Comment by sethtroisi** [comment]
Fixed, I had a problem and was syncing v16 games into a v15 bucket
