### ISSUE TITLE
Is v14 and newer eval game packages available for download?

### ISSUE THREAD

**Issue by Mewfeuille** [tensorflow/minigo#727]
Hi
I found them on minigo pub,but have only updated to v13.

Thanks.

**Comment by amj** [comment]
I'm syncing them to minigo-pub/[run]/sgf/eval.  Are they easier as a single tarball?

**Comment by Mewfeuille** [comment]
Thanks a lot.I do prefer the single file.

**Comment by Mewfeuille** [comment]
I think i'm fine with this.I have managed to download a entire folder.
