### ISSUE TITLE
who knows how to play minigo with v17 in Sabaki ?

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#731]

**Comment by amj** [comment]
have you already got our c++ engine running?  If so, running the gtp mode and passing it any of our v17 .pb files will work fine.

If not, the easiest way is probably to get the python engine running, although it will be slower.

At that point, it might be easier to play it via our minigui UI

**Comment by chunmwan** [comment]
could you give a detail example to show how to use c++ engine and python engine and how to play it via minigui UI ?
Thanks very much
