### ISSUE TITLE
./cc/configure_tensorflow.sh issue 

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#732]
when I exexuted configure_tensorflow.sh under ./cc subdir, I met below link error after compile complete:

/usr/local/cuda-10.0/bin/..//include/host_defines.h:54:2: warning: #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^~~~~~~
ERROR: /tmp/minigo_tf/tensorflow/contrib/framework/BUILD:128:1: Linking of rule '//tensorflow/contrib/framework:gen_gen_variable_ops_py_wrappers_cc' failed (Exit 1)

**Comment by amj** [comment]
the "host_defines.h" is a warning; the actual linker error is a different message, probably indicating that it can't find "libcuda.so.1" or similar.

Can you see if there are messages about missing cuda libraries at the top of the linker errors?
If so, can you print the value of LD_LIBRARY_PATH in your shell?

**Comment by chunmwan** [comment]
(tensorflow) chunmwan@alphago:~/Downloads/minigo$ env | grep LD
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/home/chunmwan/Downloads/TensorRT-4.0.1.6/lib

**Comment by chunmwan** [comment]
for (idx = 0; idx < node->hashed_peers_.size(); ++idx) {
                   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: From Compiling tensorflow/core/grappler/graph_analyzer/subgraph.cc [for host]:
tensorflow/core/grappler/graph_analyzer/subgraph.cc: In member function 'bool tensorflow::grappler::graph_analyzer::SubgraphIterator::NextIfSamePort()':
tensorflow/core/grappler/graph_analyzer/subgraph.cc:150:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (link_idx_ + 1 < link_map_it_->second.size()) {
       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/core/grappler/graph_analyzer/subgraph.cc: In member function 'bool tensorflow::grappler::graph_analyzer::SubgraphIterator::PropagateNext()':
tensorflow/core/grappler/graph_analyzer/subgraph.cc:177:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (link_idx_ >= link_map_it_->second.size()) {
          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: /tmp/minigo_tf/tensorflow/python/BUILD:1534:1: Linking of rule '//tensorflow/python:gen_array_ops_py_wrappers_cc' failed (Exit 1)
/usr/bin/x86_64-linux-gnu-ld: warning: libcublas.so.10.0, needed by bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Uarray_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or -rpath-link)

**Comment by tommadams** [comment]
For some reason, TensorFlow can't find CUDA 10 when compiling. I don't know why it would be looking for that because Minigo currently uses TensorFlow 1.11.0, which requires CUDA 9. Andrew is working on upgrading Minigo to use TF 1.13 and CUDA 10.

Do you have CUDA installed? What is the output of the following commands?

```
echo $CUDA_HOME
```

```
cat $CUDA_HOME/version.txt
```

```
ls $CUDA_HOME/lib64
```

**Comment by chunmwan** [comment]
echo $CUDA_HOME return none, but in fact , cuda 10 is installed in /usr/local/cuda
(base) chunmwan@alphago:~/Downloads/minigo$ echo $CUDA_INSTALL_DIR
/usr/local/cuda

(base) chunmwan@alphago:~/Downloads/minigo$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

(base) chunmwan@alphago:~/Downloads/minigo$ ls /usr/local/cuda/lib64
libaccinj64.so                libcufftw.so.10.0.145    libnppc_static.a        libnppig.so.10.0.130   libnvblas.so.10.0
libaccinj64.so.10.0           libcufftw_static.a       libnppial.so            libnppig_static.a      libnvblas.so.10.0.130
libaccinj64.so.10.0.130       libcuinj64.so            libnppial.so.10.0       libnppim.so            libnvgraph.so
libcublas.so                  libcuinj64.so.10.0       libnppial.so.10.0.130   libnppim.so.10.0       libnvgraph.so.10.0
libcublas.so.10.0             libcuinj64.so.10.0.130   libnppial_static.a      libnppim.so.10.0.130   libnvgraph.so.10.0.130
libcublas.so.10.0.130         libculibos.a             libnppicc.so            libnppim_static.a      libnvgraph_static.a
libcublas_static.a            libcurand.so             libnppicc.so.10.0       libnppist.so           libnvjpeg.so
libcudadevrt.a                libcurand.so.10.0        libnppicc.so.10.0.130   libnppist.so.10.0      libnvjpeg.so.10.0
libcudart.so                  libcurand.so.10.0.130    libnppicc_static.a      libnppist.so.10.0.130  libnvjpeg.so.10.0.130
libcudart.so.10.0             libcurand_static.a       libnppicom.so           libnppist_static.a     libnvjpeg_static.a
libcudart.so.10.0.130         libcusolver.so           libnppicom.so.10.0      libnppisu.so           libnvrtc-builtins.so
libcudart_static.a            libcusolver.so.10.0      libnppicom.so.10.0.130  libnppisu.so.10.0      libnvrtc-builtins.so.10.0
libcudnn.so                   libcusolver.so.10.0.130  libnppicom_static.a     libnppisu.so.10.0.130  libnvrtc-builtins.so.10.0.130
libcudnn.so.7                 libcusolver_static.a     libnppidei.so           libnppisu_static.a     libnvrtc.so
libcudnn.so.7.3.1             libcusparse.so           libnppidei.so.10.0      libnppitc.so           libnvrtc.so.10.0
libcudnn_static.a             libcusparse.so.10.0      libnppidei.so.10.0.130  libnppitc.so.10.0      libnvrtc.so.10.0.130
libcufft.so                   libcusparse.so.10.0.130  libnppidei_static.a     libnppitc.so.10.0.130  libnvToolsExt.so
libcufft.so.10.0              libcusparse_static.a     libnppif.so             libnppitc_static.a     libnvToolsExt.so.1
libcufft.so.10.0.145          liblapack_static.a       libnppif.so.10.0        libnpps.so             libnvToolsExt.so.1.0.0
libcufft_static.a             libmetis_static.a        libnppif.so.10.0.130    libnpps.so.10.0        libOpenCL.so
libcufft_static_nocallback.a  libnppc.so               libnppif_static.a       libnpps.so.10.0.130    libOpenCL.so.1
libcufftw.so                  libnppc.so.10.0          libnppig.so             libnpps_static.a       libOpenCL.so.1.1
libcufftw.so.10.0             libnppc.so.10.0.130      libnppig.so.10.0        libnvblas.so           stubs

**Comment by tommadams** [comment]
I don't really have a good suggestion here I'm afraid. Can you try setting $CUDA_HOME to $CUDA_INSTALL_DIR.

We're working on upgrading to TF 1.13.0 and CUDA 10, so maybe wait until that's ready in a few days.

**Comment by sethtroisi** [comment]
I managed to make this work with bazel 0.24.2 and TF 1.15 last night.
I did have to set `CUDNN_INSTALL_PATH=/usr/local/cuda-10.1 ./cc/configure_tensorflow`
