### ISSUE TITLE
V17 got best rating 7857? so BIG progress?

### ISSUE THREAD

**Issue by sysnotdown** [tensorflow/minigo#741]
is this rating have the same criterion with previous version?

v16 was only 4397.
v15 was only 4478
v14 was only 4868

now, v17 is 7857? really so BIG progress?

**Comment by l1t1** [comment]
https://github.com/tensorflow/minigo/issues/722

**Comment by amj** [comment]
Probably not; the rating system seen on the pages are not tethered to any external system, so it's not guaranteed that the difference in rating is a guaranteed external difference.  It might be!  We haven't done a very good job of measuring it externally yet.  But -- probably not :)
