### ISSUE TITLE
[ml_perf]validate use train.flags

### ISSUE THREAD

**Issue by delock** [tensorflow/minigo#750]
https://github.com/tensorflow/minigo/blob/master/ml_perf/reference_implementation.py#L190
train.flags should be used for training, but not validation?
```
def validate(state, holdout_glob):
  checked_run('validation',
      'python3', 'validate.py', holdout_glob,
      '--flagfile={}'.format(os.path.join(FLAGS.flags_dir, 'train.flags')),
      '--work_dir={}'.format(fsdb.working_dir()))
```

I should update the report as some flags in train.flags may not be used by validate.py.  Should put common part in a seperate file and include from both train.flags and validate.flags

**Comment by amj** [comment]
agree, a validate.flags would be helpful.
