### ISSUE TITLE
[ml_perf] The way flags files are threated are not friendly to list parameters

### ISSUE THREAD

**Issue by delock** [tensorflow/minigo#752]
When define
```
--lr_rates=0.016
--lr_rates=0.0016
--lr_rates=0.00016
--lr_boundaries=25000
--lr_boundaries=37500
```
Only the last item of same name will be reserved
In expand_flags (https://github.com/tensorflow/minigo/blob/master/ml_perf/reference_implementation.py#L96)
```
  for arg in expanded:
    flag = arg.split('=', 1)[0]
    deduped[flag] = arg
```
Should change to the following code
```
  for arg in expanded:
    flag = arg.split('=', 1)[0]
    if flag in deduped.keys():
      # in the case of --lr_rate and --lr_boundaries, same key might appear
      # multiple times, make sure they all appear in command arg list
      deduped[flag] += " {}".format(arg)
    else:
      deduped[flag] = arg
```
and .flags files should be managed in a way that flags that should not appear twice or more won't appear twice or more.

**Comment by tommadams** [comment]
Ugh, I didn't realize the Python code used list parameters: I primarily work on the C++ selfplayer and the C++ flags implementation doesn't support them.

Fortunately, the expanded flags code is only used for logging in the RL loop and doesn't affect the flags that the subprocesses run (they load the flag files directly). So, we can just remove the deduping code. I'll put together a PR this morning.
