### ISSUE TITLE
suggestion: improve readme for cc engine

### ISSUE THREAD

**Issue by godmoves** [tensorflow/minigo#760]
I've built the TensorRT and TPU engine these days, and I found some commands or
parameters that are needed but not explicitly mentioned in the readme. So I list
them here and hope this can help you guys improve the readme file.

For TRT engine, you need a `.uff` format weight, and an easy way to convert TF model
into `.uff` format is using the `convert-to-uff` tools from TensorRT.
Here is the command I used:
```
convert-to-uff v15-19x19_models_000990-cormorant.pb
```
But this may not work for v17 weight now because some layers are not supported
by TensorRT yet.

For TPU engine, except `--engine=tpu`, you also need to point out the `--tpu_name`
when you use the engine. And you may also need to change the `dual_net.py` to fit
the net structure you are using before doing the model conversion.

Although these may be trivial for people who know TRT/TPU well, point
them out in readme explicitly can help people who are not familiar with that, like me ;)

**Comment by tommadams** [comment]
Quick note: the TRT engine was written by a contributor who is no longer active. The rest of us have literally zero experience with TRT and would welcome any contributions to help improve the docs related to it :)

**Comment by godmoves** [comment]
I'm very glad to do that :)

**Comment by l1t1** [comment]
nice job
