### ISSUE TITLE
cross eval fails for v17

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#768]
2019-03-13 08:59:51.322030: F cc/dual_net/tf_dual_net.cc:62] Non-OK-status: session_->Create(graph_def) status: Invalid argument: Cannot assign a device for operation 'dense/Tensordot/GatherV2': Could not satisfy explicit device specification '/gpu:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='GPU'; Tparams in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; Tparams in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; Tparams in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; Tparams in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; Tparams in [DT_HALF]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_HALF]; Tindices in [DT_INT32]
  device='GPU'; Tparams in [DT_INT64]; Tindices in [DT_INT64]
  device='GPU'; Tparams in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_UINT64]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_UINT64]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_UINT32]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_UINT32]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_QINT16]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_QINT16]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_QUINT16]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_QUINT16]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_QINT32]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_QINT32]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_QUINT8]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_QUINT8]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_QINT8]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_QINT8]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_VARIANT]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_VARIANT]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_RESOURCE]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_RESOURCE]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_STRING]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; Tparams in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; Tparams in [DT_INT64]; Tindices in [DT_INT32]

	 [[{{node dense/Tensordot/GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/gpu:0"](dense/Tensordot/Shape, dense/Tensordot/free, dense/Tensordot/GatherV2/axis)]]
Aborted (core dumped)

**Comment by sethtroisi** [comment]
This is probably related to the speedup / slow down I was experiencing and my attempt to pinned this op to the GPU

**Comment by sethtroisi** [comment]
no, but it wasn't interesting.

**Comment by amj** [comment]
I need to know the image:tag that were used to reproduce...

**Comment by sethtroisi** [comment]
gcloud container clusters get-credentials minigo-eval --zone=europe-west4-a
