### ISSUE TITLE
AssertionError: google.cloud.logging .dist-info directory not found

### ISSUE THREAD

**Issue by bokidigital** [tensorflow/minigo#842]
pip3 install -r minigo/requirements.txt 

got the error as follows:
///////////////

Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: google.cloud.logging .dist-info directory not found

**Comment by tommadams** [comment]
I've not encountered an error like this before.

Have you created & activated a virtual environment as described [getting started](https://github.com/tensorflow/minigo#getting-started)?

Please also provide the full output of the `pip3 install` command, not just the error.

**Comment by bokidigital** [comment]
It looks cloud SDK is missed in my system, I will try first, thanks.

**Comment by bokidigital** [comment]
Here is the full log:
I am using ubuntu 16.04

I installed Cloud SDK as this link:
https://cloud.google.com/sdk/downloads#apt-get

still got the follows:
//////////////////////////////////////////////////
:~/minigo/minigo$ cat pip3_install.txt 
Collecting absl-py (from -r requirements.txt (line 1))
Collecting autopep8>=1.3 (from -r requirements.txt (line 2))
Collecting fire (from -r requirements.txt (line 3))
Collecting google.cloud.logging (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/6e/f6/bdfa6affc2705616bb172603589eaa5f36fc79362236a073fd2c2c0ff017/google_cloud_logging-1.11.0-py2.py3-none-any.whl
Collecting google.cloud.bigtable (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/b8/d3/a4670ef8d546bee30c2fc284bd211c7ce3861ae6b4df4d5d7b6382180941/google_cloud_bigtable-0.33.0-py2.py3-none-any.whl
Collecting grpcio-tools (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a4/ae/d7eafebcfa9a99ed4b3e41bf07d3de8f7f236fbfa3098aad31391d0d2b32/grpcio_tools-1.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting keras (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting numpy>=1.14.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/bb/ef/d5a21cbc094d3f4d5b5336494dbcc9550b70c766a8345513c7c24ed18418/numpy-1.16.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting protobuf (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7c/d2/581ebc3c41879aca2c4fce5c37cdb8d779c4ea79109b6da7f640735ea0a2/protobuf-3.8.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pylint (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/60/c2/b3f73f4ac008bef6e75bca4992f3963b3f85942e0277237721ef1c151f0d/pylint-2.3.1-py3-none-any.whl
Collecting sgf==0.5 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bc/91/4e878dc7a2f7e87ea9c5b33f691aef00fcb54ff58eee144485f99675af19/sgf-0.5-py2.py3-none-any.whl
Collecting six (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm>=4.17 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
Collecting pyasn1>=0.4.1 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting setuptools>=34.0.0 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Collecting oauth2client==4.1 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/2a/8f/8ad3507de44331c16af8328bd4c38992121226e2ad5947c41eb682ebbdb6/oauth2client-4.1.0-py2.py3-none-any.whl
Collecting pycodestyle>=2.4.0 (from autopep8>=1.3->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting google-cloud-core<2.0dev,>=1.0.0 (from google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/98/7f/ff56aec313787577e262d5a2e306c04aef61c5c274699ff9fb40095e6691/google_cloud_core-1.0.2-py2.py3-none-any.whl
Collecting google-api-core[grpc]<2.0.0dev,>=1.6.0 (from google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/10/d6/8b1e8d79a8a56649af3a094e3d90dd213278da942f36d831b57c0ca4a503/google_api_core-1.11.1-py2.py3-none-any.whl
Collecting grpc-google-iam-v1<0.12dev,>=0.11.4 (from google.cloud.bigtable->-r requirements.txt (line 5))
Collecting grpcio>=1.21.1 (from grpcio-tools->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/14/19/f1858ed60786ff681a5f8681448b56bffaaa87a81e9a7ca5cd075a873b35/grpcio-1.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting scipy>=0.14 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/14/49/8f13fa215e10a7ab0731cc95b0e9bb66cf83c6a98260b154cfbd0b55fb19/scipy-1.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting keras-preprocessing>=1.0.5 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting keras-applications>=1.0.6 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting pyyaml (from keras->-r requirements.txt (line 7))
Collecting h5py (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/4c/77/c4933e12dca0f61bcdafc207c7532e1250b8d12719459fd85132f3daa9fd/h5py-2.9.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting isort<5,>=4.2.5 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/1c/d9/bf5848b376e441ff358a14b954476423eeeb8c9b78c10074b7f53ce2918d/isort-4.3.20-py2.py3-none-any.whl
Collecting astroid<3,>=2.2.0 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/d5/ad/7221a62a2dbce5c3b8c57fd18e1052c7331adc19b3f27f1561aa6e620db2/astroid-2.2.5-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/a8/12/213dee680d0e7d5689e3ef20c857f72932964c9d369ec50fbc39906fc757/httplib2-0.13.0-py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl
Collecting googleapis-common-protos!=1.5.4,<2.0dev,>=1.5.3 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
Collecting pytz (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting requests<3.0.0dev,>=2.18.0 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting google-auth<2.0dev,>=0.4.0 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl
Collecting typed-ast>=1.3.0; implementation_name == "cpython" (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2a/67/d1dfc24072b40c3df20f40e45ccea63cfad2a1f31f28937ddf1a64904ba0/typed_ast-1.4.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting lazy-object-proxy (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/1f/f4/65eb90d5c1d22861d80faac4af74e3adc41cd63c8aea198e21a00372f875/lazy_object_proxy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting wrapt (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Installing collected packages: six, absl-py, pycodestyle, autopep8, fire, setuptools, protobuf, googleapis-common-protos, pytz, certifi, idna, urllib3, chardet, requests, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, grpcio, google-api-core, google-cloud-core, google.cloud.logging, grpc-google-iam-v1, google.cloud.bigtable, grpcio-tools, numpy, scipy, keras-preprocessing, h5py, keras-applications, pyyaml, keras, isort, typed-ast, lazy-object-proxy, wrapt, astroid, mccabe, pylint, sgf, tqdm, httplib2, oauth2client
rsa@rsa-VirtualBox:~/minigo/minigo$ pip3 install -r requirements.txt 
Collecting absl-py (from -r requirements.txt (line 1))
Collecting autopep8>=1.3 (from -r requirements.txt (line 2))
Collecting fire (from -r requirements.txt (line 3))
Collecting google.cloud.logging (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/6e/f6/bdfa6affc2705616bb172603589eaa5f36fc79362236a073fd2c2c0ff017/google_cloud_logging-1.11.0-py2.py3-none-any.whl
Collecting google.cloud.bigtable (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/b8/d3/a4670ef8d546bee30c2fc284bd211c7ce3861ae6b4df4d5d7b6382180941/google_cloud_bigtable-0.33.0-py2.py3-none-any.whl
Collecting grpcio-tools (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a4/ae/d7eafebcfa9a99ed4b3e41bf07d3de8f7f236fbfa3098aad31391d0d2b32/grpcio_tools-1.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting keras (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting numpy>=1.14.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/bb/ef/d5a21cbc094d3f4d5b5336494dbcc9550b70c766a8345513c7c24ed18418/numpy-1.16.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting protobuf (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7c/d2/581ebc3c41879aca2c4fce5c37cdb8d779c4ea79109b6da7f640735ea0a2/protobuf-3.8.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pylint (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/60/c2/b3f73f4ac008bef6e75bca4992f3963b3f85942e0277237721ef1c151f0d/pylint-2.3.1-py3-none-any.whl
Collecting sgf==0.5 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bc/91/4e878dc7a2f7e87ea9c5b33f691aef00fcb54ff58eee144485f99675af19/sgf-0.5-py2.py3-none-any.whl
Collecting six (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm>=4.17 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
Collecting pyasn1>=0.4.1 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting setuptools>=34.0.0 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Collecting oauth2client==4.1 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/2a/8f/8ad3507de44331c16af8328bd4c38992121226e2ad5947c41eb682ebbdb6/oauth2client-4.1.0-py2.py3-none-any.whl
Collecting pycodestyle>=2.4.0 (from autopep8>=1.3->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting google-api-core[grpc]<2.0.0dev,>=1.6.0 (from google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/10/d6/8b1e8d79a8a56649af3a094e3d90dd213278da942f36d831b57c0ca4a503/google_api_core-1.11.1-py2.py3-none-any.whl
Collecting google-cloud-core<2.0dev,>=1.0.0 (from google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/98/7f/ff56aec313787577e262d5a2e306c04aef61c5c274699ff9fb40095e6691/google_cloud_core-1.0.2-py2.py3-none-any.whl
Collecting grpc-google-iam-v1<0.12dev,>=0.11.4 (from google.cloud.bigtable->-r requirements.txt (line 5))
Collecting grpcio>=1.21.1 (from grpcio-tools->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/14/19/f1858ed60786ff681a5f8681448b56bffaaa87a81e9a7ca5cd075a873b35/grpcio-1.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting scipy>=0.14 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/14/49/8f13fa215e10a7ab0731cc95b0e9bb66cf83c6a98260b154cfbd0b55fb19/scipy-1.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting keras-preprocessing>=1.0.5 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting pyyaml (from keras->-r requirements.txt (line 7))
Collecting keras-applications>=1.0.6 (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting h5py (from keras->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/4c/77/c4933e12dca0f61bcdafc207c7532e1250b8d12719459fd85132f3daa9fd/h5py-2.9.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting mccabe<0.7,>=0.6 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/1c/d9/bf5848b376e441ff358a14b954476423eeeb8c9b78c10074b7f53ce2918d/isort-4.3.20-py2.py3-none-any.whl
Collecting astroid<3,>=2.2.0 (from pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/d5/ad/7221a62a2dbce5c3b8c57fd18e1052c7331adc19b3f27f1561aa6e620db2/astroid-2.2.5-py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client==4.1->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/a8/12/213dee680d0e7d5689e3ef20c857f72932964c9d369ec50fbc39906fc757/httplib2-0.13.0-py3-none-any.whl
Collecting googleapis-common-protos!=1.5.4,<2.0dev,>=1.5.3 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
Collecting pytz (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting requests<3.0.0dev,>=2.18.0 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting google-auth<2.0dev,>=0.4.0 (from google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl
Collecting typed-ast>=1.3.0; implementation_name == "cpython" (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2a/67/d1dfc24072b40c3df20f40e45ccea63cfad2a1f31f28937ddf1a64904ba0/typed_ast-1.4.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting lazy-object-proxy (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/1f/f4/65eb90d5c1d22861d80faac4af74e3adc41cd63c8aea198e21a00372f875/lazy_object_proxy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting wrapt (from astroid<3,>=2.2.0->pylint->-r requirements.txt (line 10))
Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.6.0->google.cloud.logging->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Installing collected packages: six, absl-py, pycodestyle, autopep8, fire, setuptools, protobuf, googleapis-common-protos, pytz, certifi, idna, chardet, urllib3, requests, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, grpcio, google-api-core, google-cloud-core, google.cloud.logging, grpc-google-iam-v1, google.cloud.bigtable, grpcio-tools, numpy, scipy, keras-preprocessing, pyyaml, h5py, keras-applications, keras, mccabe, isort, typed-ast, lazy-object-proxy, wrapt, astroid, pylint, sgf, tqdm, httplib2, oauth2client
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: google.cloud.logging .dist-info directory not found

**Comment by brilee** [comment]
Hm, just realized the instructions don't actually have lines that create and activate a virtualenv. Can you run

```
python3 -m venv .
./bin/activate
```
to create and activate a virtualenv? This step should happen before running `pip install -r requirements.txt`

**Comment by bokidigital** [comment]
After executed this line:
python3 -m venv .

the bin folder doesn't contain 'activate' file.

What it has in bin folder is:
easy_install
pip
pip3.5
python3
easy_install-3.5
pip3
python
///

Thanks.

**Comment by tommadams** [comment]
I don't know if it matters but I've always used a different command to generate my virtual envs: `virtualenv --system-site-packages -p python3 $HOME/.venvs/minigo`

I've experienced an issue where the virtual env didn't get fully created the first time I ran the command, but worked after running the same command a second time.

**Comment by bokidigital** [comment]
I still see this issue, after executed this line:
virtualenv --system-site-packages -p python3 $HOME/.venvs/minigo

**Comment by tommadams** [comment]
Have you tried running the command twice? It sounds ridiculous but worked for me when I ran into a similar issue in the past. Other than that advice, I don't think I can be much help, this sounds like a virtualenv problem.

**Comment by bokidigital** [comment]
I tested on ubuntu 16.04, it doesn't work.
I tested on ubuntu 18, it works.
