### ISSUE TITLE
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bokidigital** [tensorflow/minigo#843]
OS: ubuntu 18.04.1

After executed: /test.sh

I got:

ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

**Comment by brilee** [comment]
Have you installed CUDA 10?

**Comment by bokidigital** [comment]
I installed it by this link:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal

**Comment by brilee** [comment]
You'll have to double check that all the .so objects are in the right place - the error message points at an incorrect or missing installation

**Comment by bokidigital** [comment]
I did a clean installation, maybe README can provide a full of steps.

**Comment by tommadams** [comment]
Sorry for the delayed response, I'm on vacation with limited internet access for the rest of the week. That link you posted is for CUDA 10.1, not 10.0.

The Minigo README.md does actually contain a link to the download page for the correct version of CUDA.

**Comment by bokidigital** [comment]
I tested CUDA 10.0 in a clean system today; However, it got the same result as follows:
OS: ubuntu 18.04

./test.sh

///////////////////////////////////////////
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/run_tests.py", line 23, in <module>
    import test_dual_net
  File "/home/rsa/minigo/minigo/tests/test_dual_net.py", line 20, in <module>
    import dual_net
  File "./dual_net.py", line 29, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by tommadams** [comment]
What happens if you try importing TensorFlow directly instead of running the test script?

`python -c "import tensorflow"`

**Comment by bokidigital** [comment]
python -c "import tensorflow"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

**Comment by tommadams** [comment]
What about `python3 -c "import tensorflow"`

**Comment by bokidigital** [comment]
python3  -c "import tensorflow"

Traceback (most recent call last):
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py",
line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py",
line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py",
line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such
file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py",
line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint:
disable=unused-import
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py",
line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py",
line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py",
line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py",
line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File
"/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py",
line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such
file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by tommadams** [comment]
You've got a problem with your TensorFlow install, which isn't really related to Minigo. I suggest you read through that doc if you haven't already done so and follow whatever its recommended steps are for getting help.

**Comment by bokidigital** [comment]
I followed the steps in https://github.com/tensorflow/minigo to install tensorflow:

pip3 install "tensorflow-gpu==1.13.1"

on a clean system, actually, I don't know which step is wrong.

**Comment by tommadams** [comment]
We done maintain a full guide to installing tensorflow in our README, you should follow the guide on the tensorflow website: https://www.tensorflow.org/install/gpu

**Comment by bokidigital** [comment]
After following the steps in:

https://www.tensorflow.org/install/gpu 

The error mentioned in this thread is gone.

/////

2019-06-26 09:12:26.754448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15216 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:1e:00.0, compute capability: 6.0)
I0626 09:12:26.760015 139877677930304 dual_net.py:169] TPU inference is supported on C++ only. DualNetwork will ignore use_tpu=True
I0626 09:12:27.955729 139877677930304 saver.py:1270] Restoring parameters from /tmp/tmpmo7zaxss/models/000001-jupiter
I0626 09:12:28.051309 139877677930304 utils.py:86] Loading weights: 3.891 seconds
2019-06-26 09:12:28.090563: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Finished game 0 W+1.5
Completed integration test!
