### ISSUE TITLE
Trunk layer = 5 for 19x19 in ml_perf reference implementation

### ISSUE THREAD

**Issue by delock** [tensorflow/minigo#853]
https://github.com/tensorflow/minigo/blob/master/ml_perf/flags/19/architecture.flags#L5
The value is 5.  According to minigo code, this value is usually 19 for 19x19 board.

Is this number (5) intended or just a dummy value?  how about other value such as conv_width and fc_width?

**Comment by tommadams** [comment]
That flag file is just a placeholder. We have yet to determine what any of those values should be for 19x19.
