### ISSUE TITLE
change the way c++ compile

### ISSUE THREAD

**Issue by gms2009** [tensorflow/minigo#854]
./cc/configure_tensorflow.sh
always end up with download error
hope changes made in BUILD file so the c++ part can be move to tensorflow/examples directory and compile with bazel build tensorflow/examples/cc/...

**Comment by gms2009** [comment]
no need

**Comment by amj** [comment]
we're working a proper solution for this, how did you end up working around it?

**Comment by gms2009** [comment]
Somehow the download completed, and it is tensorflow 1.13 rc2 in the /tmp/minigo_tf, I replace it with tensorflow 1.13.2, tweek the cc/configure_tensorflow.sh to disable the git download, but the later process has "tensorflow dir not found" error. I will rerun to make sure
