### ISSUE TITLE
SGF Analysis tools

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#9]
It's easy to grab a bunch of SGFs with gsutil cp ... After that, we're looking at statistics largely by doing 'grep'... which is getting slower as we add more stuff to our SGF comments.

It'd be nice to:
a. See opening move stats per generation, with reflection/symmetry taken into account. This could be made pretty fast by only reading the head of the file until the 1st move, etc.
b. Figure out what moves the network is moving towards/away. This involves looking at how the visit counts after search match with the priors -- if a move (on the whole) is getting more visits than the priors suggested, after d-noise, then we can expect that move to be more represented in the next generation, & vice versa.
c. It'd be nice to look for the 'most surprising moves' in a game -- e.g., greatest difference from policy prior and final exploration rate.
d. Similarly, there are some nice questions about the times in a game when it has many options vs when it only has one or two; some nice ways to explore these would be good.

**Comment by marcocalignano** [comment]
I found these tools for SGF file we could use for the analysis tool Is GPL 2  or later compatible with the Apache 2 license? 
https://github.com/lightvector/leela-analysis/tree/master/sgftools

**Comment by amj** [comment]
@sethtroisi 's cloudygo takes care of most of the original list, and then some.  I know he's been chatting with lightvector but i don't know if he was using those tools.
