### ISSUE TITLE
Create a Google Group for Discussions

### ISSUE THREAD

**Issue by Kashomon** [tensorflow/minigo#90]
Currently, our repo is where we track discussions (via Issues). We could create a Google Group (i.e., a mailing list) or use some other discussion forum (Slack). We don't want to fragment discussion, but it depends on what the community wants and how much participation we have (we don't want empty rooms).

This is a discussion issue -- feel free to chime in. Currently we don't have any plans here, but that could change based on community feedback.

**Comment by brilee** [comment]
I haven't felt limited by Github Issues yet; this seems like a simple enough communications medium for now. If we need more freeform discussion, I think reddit/r/cbaduk would be a good place to hold discussion.

**Comment by sethtroisi** [comment]
A lot of discussion ended up in discord which is working well
https://discordapp.com/channels/417022162348802048/433085673088614401
