### ISSUE TITLE
Comment or code problem.

### ISSUE THREAD

**Issue by marcocalignano** [tensorflow/minigo#91]
I was reading the code in mtcs,py and here https://github.com/tensorflow/minigo/blob/e7e686d1f44178aba4c9286848cc44842a1cec1b/mcts.py#L239
I found that the comment does not fit the code. I was just wondering which is wrong.
.95 would be ok if you have a value of prob < 1 but at this point is equal to child_n that can also be > 1 so I guess the "squash" operation should be after the probability calculation. Or am I missing something?

**Comment by amj** [comment]
raising to an exponent < 1 will still 'squash' the numbers closer together, compressing their ratios.

**Comment by killerducky** [comment]
The confusion is over the comment: "exponentiate the probabilities by a temperature slightly larger than unity". But the code is hiding the true value of T. T = 1/0.95, not 0.95.

**Comment by marcocalignano** [comment]
@killerducky Can you point me to the code where the true value of T is calculated? I just see this https://github.com/tensorflow/minigo/blob/e7e686d1f44178aba4c9286848cc44842a1cec1b/mcts.py#L244

**Comment by killerducky** [comment]
They just wrote it in a different form. It's the same as this:

```
temp = 1.0/0.95
probs = probs ** (1/temp)
```

**Comment by marcocalignano** [comment]
@amj yes, if the number is > 1 otherwise it does the opposite.

**Comment by amj** [comment]
@marcocalignano not sure what you're saying.  If the concern is that we are raising the raw visit counts to an exponent < 1, that has the effect of 'squashing' the numbers.

i.e., [1, 10, 100] ** 0.9 = [1, 7.9, 63]

This is also true for numbers < 1
[0.01, 0.1, 1] ** .9 = [.02, .13, 1]

the arithmetic ratios are smaller.

**Comment by marcocalignano** [comment]
@amj Ok sorry if the arithmetic ratios is what count you are right I was just a bit disturbed by the fact  that  ifthe count is less that 1 you increase the number, if it it bigger than 1 you decrease it.
