### ISSUE TITLE
dual_net_edge_tpu error

### ISSUE THREAD

**Issue by anotheros** [tensorflow/minigo#912]
1.  https://coral.withgoogle.com/docs/accelerator/get-started/ According to this, it is ok.
2. https://coral.withgoogle.com/projects/minigo/ When I did this, there was a problem.

python3 minigui/serve.py --control minigui/control/minigo_edgetpu.ctl &

> Starting engine "minigo_edgetpu"
> minigo_edgetpu(stderr): Fatal Python error: Segmentation fault
> minigo_edgetpu(stderr):
> minigo_edgetpu(stderr): Current thread 0x00007f72210d7740 (most recent call first):
> minigo_edgetpu(stderr):   File "/usr/local/lib/python3.6/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 300 in __init__
> minigo_edgetpu(stderr):   File "./minigo/dual_net_edge_tpu.py", line 31 in __init__
> minigo_edgetpu(stderr):   File "gtp.py", line 49 in make_gtp_instance
> minigo_edgetpu(stderr):   File "gtp.py", line 85 in main
> minigo_edgetpu(stderr):   File "./minigo/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
> minigo_edgetpu(stderr):   File "./minigo/lib/python3.6/site-packages/absl/app.py", line 299 in run
> minigo_edgetpu(stderr):   File "gtp.py", line 93 in <module>
> minigo_edgetpu: stderr thread died
> 
> 

Is the tpu driver update caused?

**Comment by anotheros** [comment]
No EdgeTPU libs found.

when i run  "sh ./minigui/edgetpu/install_requirements.sh"

but this is OK https://coral.withgoogle.com/docs/accelerator/get-started/

**Comment by jeremylorino** [comment]
followed the [edge tpu walkthrough](https://coral.withgoogle.com/projects/minigo/) while ssh'd into the dev board.

opened the kiosk page and received the following error

```
= __NEW_TOKEN__ minigo_edgetpu-1573714740134
report_search_interval 50
=
clear_board
=
genmove b
Traceback (most recent call last):
  File "/home/mendel/minigo/gtp_engine.py", line 171, in handle_msg
    _print_success(msg_id, handler(*args))
  File "/home/mendel/minigo/gtp_cmd_handlers.py", line 256, in cmd_genmove
    result = super().cmd_genmove(color)
  File "/home/mendel/minigo/gtp_cmd_handlers.py", line 84, in cmd_genmove
    move = self._player.suggest_move(self._player.get_position())
  File "/home/mendel/minigo/strategies.py", line 137, in suggest_move
    self.tree_search()
  File "/home/mendel/minigo/gtp_cmd_handlers.py", line 276, in _tree_search_wrapper
    leaves = self._tree_search(parallel_readouts)
  File "/home/mendel/minigo/strategies.py", line 209, in tree_search
    [leaf.position for leaf in leaves])
  File "/home/mendel/minigo/dual_net_edge_tpu.py", line 56, in run_many
    processed = list(map(features_lib.extract_features, positions))
TypeError: extract_features() missing 1 required positional argument: 'features'
? extract_features() missing 1 required positional argument: 'features'
```
![Screenshot 2019-11-14 at 1 08 59 AM](https://user-images.githubusercontent.com/5013726/68834454-6e548b80-067b-11ea-8474-459a1c64d91e.png)

**Comment by tommadams** [comment]
My bad. I've been making significant changes to the model code to support different types of input features and it looks like I broke this along the way.

`features_lib.extract_features` now takes two arguments. The input board positions, and the input feature type to generate. Can you try adding `import functools` to the top of `dual_net_edge_tpu.py` and then changing the following line:

```processed = list(map(features_lib.extract_features, positions))```

to:

```processed = list(map(functools.partial(features_lib.extract_features, features=features_lib.AGZ_FEATURES), positions))```

**Comment by jeremylorino** [comment]
Thanks! That did work but I did receive the following deprecation warning:

```
W1117 03:19:23.093821 281472803090896 warning.py:43] From /home/mendel/minigo/dual_net_edge_tpu.py:63: The name RunInference will be deprecated. Please use run_inference instead.
```
