### ISSUE TITLE
main.evaluate needs updating for vlosses, currently does not run.

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#93]
Hi, 

I used the bootstrap model to test the main.evaluation() function. The black and white players are the same model. However, during running, an error happened:

 File "./try.py", line 13, in <module>
    main.evaluate(black_model = black_model, white_model = white_model, output_dir = out_dir, readouts = 10, games = 1, verbose = 3)
  File "/home/xliu/minigo/main.py", line 113, in evaluate
    black_net, white_net, games, readouts, verbose)
  File "/home/xliu/minigo/evaluation.py", line 66, in play_match
    prob, val, up_to=pair[num_moves % 2].root)
  File "/home/xliu/minigo/mcts.py", line 197, in incorporate_results
    assert not self.position.is_game_over()
AssertionError

I can not figure out the reason.  Can anyone help me? Before this error, there was another error at the end of evaluation.py, that says the MCT object does not have the is_done() attribute. I fixed it by changing p[0].is_done() and p[1].is_done() to p[0].root.is_done() and p[1].root.is_done(). 

Thank you for your help.

**Comment by amj** [comment]
Hmm, it looks like our evaluation.py code didn't get updated when we made our change to use virtual losses.  Instead of doing multi-game parallelization, we should rewrite this to just play one game at a time for N games.

Thanks for the bug report!

**Comment by Kashomon** [comment]
I'll take a look. thanks @weedwind

**Comment by weedwind** [comment]
Hi, amj,

Thank you very much for your reply. I want to take another way to let my 2 models to play against each other. My script is:

#!/bin/bash

BLACK="python3 main.py gtp -l models/000000-bootstrap"
WHITE="python3 main.py gtp -l models/000001-model"
TWOGTP="gogui-twogtp -black \"$BLACK\" -white \"$WHITE\" -games 10\
  -size 9 -alternate -sgffile gnugo"
gogui -size 9 -program "$TWOGTP" -computer-both -auto

However, it says "The command genmove b sent to the Go program failed." Does that mean I can not use 2 of my own models in gogui?


Thank you so much.

**Comment by amj** [comment]
@weedwind it looks like gogui is suppressing the failure message from the gtp program playing black, and i'm not sure what you have to do to get it to display them.  If i had to guess, i'd say you'd need to look in gogui for the console output, which might provide additional information about what happened.

**Comment by weedwind** [comment]
It looks like it's a GPU issue. When I ran the script above, the two models made GPU out of memory

**Comment by amj** [comment]
interesting!  have you tried it with the change from [this commit?](https://github.com/tensorflow/minigo/commit/73713123f449cb11da6790caeb0ab002556338fe)

**Comment by weedwind** [comment]
@amj I just tried, it worked. Thank you very much.

**Comment by brilee** [comment]
I believe this is fixed with https://github.com/tensorflow/minigo/pull/111

**Comment by amj** [comment]
Yes, fixed in #111 !  @weedwind if you'd like to try the evaluation program directly, something like 
`python main.py evaluate /path/to/model1 path/to/model2 --readouts 100 --games 8` should work
