### ISSUE TITLE
Where to see who wins when playing with gnu go

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#94]
Hi, I know this is a very naive question. I am new to Go. I played a game using my model against gnu go following the command in the readme (the twogtp command) of this repository. Anyone can tell me how to check who wins?

The gnugo.sgf is below:

(;FF[4]CA[UTF-8]AP[gogui-twogtp:1.4.9]SZ[9]
KM[6.5]PB[GNU Go]PW[Somebot-000001-model]DT[2018-02-15]
C[Black command: gnugo --mode gtp
White command: python3 main.py gtp -l models/000001-model
Black version: 3.8
White version: 0.1
Result[Black\]: B+78.5
Result[White\]: ?
Host: xliu-linux3 (Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz)
Date: February 15, 2018 4:09:07 PM PST]
;B[ee];W[dg];B[cf];W[di];B[cd];W[fa];B[gb];W[ig];B[gg];W[ei]
;B[ff];W[gi];B[hh];W[fc];B[fb];W[eh];B[cg];W[if];B[he];W[cc]
;B[bc];W[ie];B[hd];W[da];B[dc];W[ih];B[ch];W[ga];B[ha];W[ad]
;B[ed];W[be];B[bd];W[de];B[df];W[fg];B[hi];W[eb];B[hb];W[gd]
;B[db];W[ef];B[gh];W[bh];B[ci];W[ca];B[cb];W[ac];B[ab];W[af]
;B[ce];W[id];B[ic];W[ag];B[ba];W[gf];B[fe];W[ah];B[fh];W[ec]
;B[hf];W[ii];B[hg];W[ae];B[hc];W[ig];B[dd];W[if];B[];W[ge]
;B[];W[ie];B[];W[id];B[];W[ib];B[];W[])

And there is a gnugo.dat file:

# Black: GNU Go
# BlackCommand: gnugo --mode gtp
# BlackLabel: GNU Go
# BlackVersion: 3.8
# Date: February 15, 2018 4:08:51 PM PST
# Host: xliu-linux3 (Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz)
# Komi: 6.5
# Referee: -
# Size: 9
# White: Somebot-000001-model
# WhiteCommand: python3 main.py gtp -l models/000001-model
# WhiteLabel: Somebot-000001-model
# WhiteVersion: 0.1
# Xml: 0
#
#GAME   RES_B   RES_W   RES_R   ALT     DUP     LEN     TIME_B  TIME_W  CPU_B   CPU_W   ERR     ERR_MSG
0       B+78.5  ?       ?       0       -       78      10.1    4.8     10.2    0       0

**Comment by amj** [comment]
at the top of the sgf it says: `Result[Black]: B+78.5`
More details on the sgf specifications can be found [here](https://www.red-bean.com/sgf/)
