### ISSUE TITLE
selfplay function only plays 1 game, can we make it play many games in one call

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#96]
Hi, 
Right now the selfplay function only plays 1 game per call. I changed it to the following to make it play many games in one call. I am wondering can we just load the model once and let it play many games like this code? This is a lot faster than loading the model every time we play a game.

def selfplay(
        load_file: "The path to the network model files",
        output_dir: "Where to write the games"="data/selfplay",
        holdout_dir: "Where to write the games"="data/holdout",
        output_sgf: "Where to write the sgfs"="sgf/",
        readouts: 'How many simulations to run per move'=100,
        verbose: '>=2 will print debug info, >=3 will print boards' = 1,
        resign_threshold: 'absolute value of threshold to resign at' = 0.95,
        holdout_pct: 'how many games to hold out for evaluation' = 0.05):
    _ensure_dir_exists(output_sgf)
    _ensure_dir_exists(output_dir)

   # Only load model once
    with timer("Loading weights from %s ... " % load_file):
        network = dual_net.DualNetwork(load_file)
        network.name = os.path.basename(load_file)

   # Let the model play many games
    for i in range(5000):
      with timer("Playing game"):
          player = selfplay_mcts.play(
            network, readouts, resign_threshold, verbose)

      output_name = '{}-{}'.format(int(time.time()), socket.gethostname())
      game_data = player.extract_data()
      with gfile.GFile(os.path.join(output_sgf, '{}.sgf'.format(output_name)), 'w') as f:
         f.write(player.to_sgf())

      tf_examples = preprocessing.make_dataset_from_selfplay(game_data)

      # Hold out 5% of games for evaluation.
      if random.random() < holdout_pct:
        fname = os.path.join(holdout_dir, "{}.tfrecord.zz".format(output_name))
      else:
        fname = os.path.join(output_dir, "{}.tfrecord.zz".format(output_name))

      preprocessing.write_tf_examples(fname, tf_examples)

**Comment by Kashomon** [comment]
> Right now the selfplay function only plays 1 game per call.

I seem to recall that we did this because there was some memory leak somewhere. @amj -- do you remember the reason for playing one game / call?

>  This is a lot faster than loading the model every time we play a game.

Did you get a chance to profile the change? What's the difference?

**Comment by weedwind** [comment]
@Kashomon If I need to reload the model for each game, it takes time to distribute the model across gpus compared with only loading it once.

**Comment by amj** [comment]
no it's not a memory leak, but we'd need to change our cluster management/expectations around the pod lifecycle.  Actually, now that we check how many games are played at the beginning of selfplay and quit accordingly, this could work.

I think the savings here are the startup costs + the scheduling costs from k8s, times the number of nodes.  On 9s that's 5s out of ~300s or ~1%.  On 19x it would probably be less, maybe 20s out of 1200?

Also, @weedwind are you loading the model from a local file?  Or a gcs bucket?

(Distributed GPUs!  What kind of performance numbers are you seeing vs using a single GPU?)

**Comment by weedwind** [comment]
@amj I can run the code both from my local machine with 2 1080 GPUs, and also on Amazon AWS (16 K80). When I say "distribute", I simply mean the startup cost to copy the models to these GPUs.

**Comment by weedwind** [comment]
@amj Using more gpus does not improve the speed, probably because I was training a 9 by 9 board, and loading the model to 16 gpus took more time than 2 gpus.

**Comment by brilee** [comment]
We used to play 8 or more games in parallel; we dialed it down to 1 for data freshness reasons - you don't want to be generating game data using model generation 17 when generation 18 or 19 is available.

Also, we were playing 9s on CPU, which mean that the overhead was not that big relative to the CPU playout time for 1 game. The balance is skewed towards higher overhead with a 1080 as you can see.

**Comment by amj** [comment]
@weedwind right, this code is for the 19x19 pipeline, where a worker plays a game, exits, and a new worker starts up, checks for if a newer models exists, etc.

Are there further issues on this?  it looks like you were able to play multiple games without issue?  Please re-open if there are further questions
