### ISSUE TITLE
If the SGF says W+R (or B+R), who wins?

### ISSUE THREAD

**Issue by weedwind** [tensorflow/minigo#97]
On the top of a sfg file, the result is:

Result[Black\]: W+R
Result[White\]: W+R

I think this means white wins. However, if I use the command:

gnugo --score estimate -l sgf_file_name

it says: Black wins by 1.5 points

So who wins by W+R?

Thank you very much.

**Comment by amj** [comment]
W+R = White by Resignation.

Gnugo might be wrong :)
