### ISSUE TITLE
Minigo not working on Coral accelerator

### ISSUE THREAD

**Issue by Rhys2231** [tensorflow/minigo#970]
I am very new to tensor flow so I bought the coral usb accelerator to learn it. I first started setting it up with this guide https://coral.ai/docs/accelerator/get-started/ , and I was able to do the image classification example. Then I followed this guide https://coral.ai/projects/minigo/ to setup mini. However, when I entered this command python3 -c 'import edgetpu; print("OK")' , it showed an error, so I installed the library by sudo apt-get update && sudo apt-get install python3-edgetpu. I then moved forward and finish all of the instructions below, but when I go to http://localhost:5001/kiosk.html , it didn't play itself, it just shows the board and the terminal did not show any error. The similar happened with http://localhost:5001/lw_demo.html, I can play the first move but the AI didn't do anything. I am very frustrated as I thought this is easy for starters learn simple tensor flow. Please send help.

**Comment by brilee** [comment]
Have you tried toggling the players in the kiosk window? I believe it defaults to Human vs. Human, and if you click the Human button, it'll switch to Computer generated moves.

**Comment by Rhys2231** [comment]
I’m sure it’s in Minigo vs Human. Also Minigo verses itself doesn’t work too

**Comment by tommadams** [comment]
Sorry to hear that it isn't working. We've been hammering on other stuff recently and it's likely I broke something. I'll try and get my hands on a Coral accelerator this week and see if I can reproduce the problem.

**Comment by tommadams** [comment]
This should be fixed now. Please do a `git pull` and run `python3 minigui/serve.py --control minigui/control/minigo_edgetpu.ctl &` again.

Let us know if you run into any other issues, and have fun!
