### ISSUE TITLE
How strong is the model in kyu/dan?

### ISSUE THREAD

**Issue by smolendawid** [tensorflow/minigo#980]
Excuse me if I can find this info somewhere but I wasn't able to do it. What level for the current model is estimated?

**Comment by sethtroisi** [comment]
A brief answer is

A lot of strength comes down to number of playouts (which depends on time / hardware).

With even modest hardware I suspect we are 3p+ and on good hardware all the strong engines seem to be able to win regularly against 7p+

**Comment by amj** [comment]
@sethtroisi 3p/7p are no longer indications of strength; they are measures of achievement. 

@smolendawid We're definitely past pro level in match settings.  A github repo at one point tracked AI strength: https://github.com/breakwa11/GoAIRatings  but it doesn't appear to have been updated lately.

**Comment by smolendawid** [comment]
Great to know, congratulations to all the team. Thank for the answer

**Comment by smolendawid** [comment]
@sethtroisi by a number of playouts you mean `--num_readouts`? I'd like to play against a strong model but `000737-fury` with 10 readouts doesn't seem too strong.

**Comment by tommadams** [comment]
10 readouts is far too low. You should try at least 800 or 1600

**Comment by smolendawid** [comment]
And do you know how many readouts is possible on Raspberry PI in some reasonable time, let's say 5-10 sec?

**Comment by tommadams** [comment]
I don't know about the full model. But we trained a quantized model that can be run on an Edge TPU, which is very fast: https://coral.ai/projects/minigo/
