### ISSUE TITLE
How to communicate with engine easily outside stdin

### ISSUE THREAD

**Issue by smolendawid** [tensorflow/minigo#983]
Hi

I have an idea that I'm not able to realize without a brief help.

I can see that there is a serve.py script that creates the server, but I don't know how to communicate with it. Also creating the engine in gpt.py without using the FLAGS as a global object is not easy for me.

What I'd like to be able to do is:
1. Set the current state of some Go game
2. Generate the best move according to the model

I am able to pass the .`sgf` file each time the game state changes, and I am able to run `genmove` command in stdin in `gtp.py` script. But I can't figure out how to communicate with the engine outiside the `stdin`.

Could somebody please tell me what are the possibilities to communicate with the engine using simple API? Should I write it, how to set flags, or maybe I should use the `serve.py` code, but then how. 

I think a simple suggestion/explanation would let me proceed.

Thank you

**Comment by amj** [comment]
If you're trying to write a script, probably extending gtp.py is the place to do it.
serve.py is used for our front-end, minigui.

The gtp.py script is a straightforward way to load the model in the python engine.
If you need performance, you can build the gtp binary in cc/ and script inputs/outputs to that engine.

GTP is pretty strict about what it can output to stdout -- not much!  Most of the useful output we put on stderr.

So you could:
1. write a script to run inferences with the model directly (lots of examples in oneoffs/)
2. write a script to interact with the engine via custom gtp command handlers (extending gtp.py)
3. write a script to interact with the engine via stdin and scrape stderr/stdout for the outputs

let me know if this helps!

**Comment by smolendawid** [comment]
Yes, it looks ok. I don't know why I wasn't able to understand it. I think the documentation could be better, there's a lot of scripts without a single word about usage. Thanks for pointing out `oneoffs` directory
